
ST10=
[{"name":"야옹몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - 렛서형","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【어택 시】 옐로인 자신의 디지몬이 있을 때, 《1 드로우》 (자신의 덱에서 카드를 1장 드로우한다). 그렇게 했을 때, 자신의 패를 1장 파기한다."],"card_number":"ST10-01","card_level":"U","image_link":"https://i.imgur.com/KVtCKUp.png","LOCAL_NUMBER":16000},
{"name":"플롯트몬","color":"황","level":3,"type":"디지몬","attribute":"성장기 백신종 포유류형","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["-","-","【자신의 턴 종료 시】이 디지몬과 자신의 다른 디지몬으로, 코스트를 지불하여 패의 디지몬 카드로 조그레스 진화할 수 있다."],"card_number":"ST10-02","card_level":"C","image_link":"https://i.imgur.com/aufXY1a.png","LOCAL_NUMBER":16001},
{"name":"로프몬","color":"황","level":3,"type":"디지몬","attribute":"성장기 데이터종 짐승형","dp":4000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["-","-","-"],"card_number":"ST10-03","card_level":"C","image_link":"https://i.imgur.com/SFlSEYD.png","LOCAL_NUMBER":16002},
{"name":"가트몬","color":"황자","level":4,"type":"디지몬","attribute":"성숙기 백신종 성수형","dp":4000,"cost":5,"evolution_cost":["Lv.3~3","Lv.3~3"],"effect":["【등장 시】 자신의 덱 위에서부터 3장 오픈한다. 그중 옐로와 퍼플의 디지몬 카드 1장씩을 패에 추가한다. 남은 카드는 원하는 순서대로 덱 아래로 되돌린다. \n【자신의 턴】이 디지몬이 특징으로 「대천사형」 또는 「타천사형」을 가진 카드로 진화할 때, 지불하는 진화 코스트를 -2 한다.","-","【자신의 턴 종료 시】이 디지몬과 자신의 다른 디지몬으로, 코스트를 지불하여 패의 디지몬 카드로 조그레스 진화할 수 있다."],"card_number":"ST10-04","card_level":"SR","image_link":"https://i.imgur.com/gpnPWWy.png","LOCAL_NUMBER":16003},
{"name":"엔젤우몬","color":"황","level":5,"type":"디지몬","attribute":"완전체 백신종 대천사형","dp":6000,"cost":6,"evolution_cost":["Lv.4~3","Lv.4~3"],"effect":["【등장 시】 다음 상대의 턴 종료 시까지 상대 디지몬 1마리에게 《시큐리티 어택 -2》 (이 디지몬이 체크하는 시큐리티의 매수 -2)를 준다.","-","【자신의 턴】퍼플인 자신의 디지몬이 있는 동안, 이 디지몬은 《시큐리티 어택 +1》 (이 디지몬이 체크하는 시큐리티의 매수 +1)을 얻는다."],"card_number":"ST10-05","card_level":"R","image_link":"https://i.imgur.com/GLseV4O.png","LOCAL_NUMBER":16004},
{"name":"마스테몬","color":"황자","level":6,"type":"디지몬","attribute":"궁극체 백신종 천사형","dp":13000,"cost":13,"evolution_cost":["Lv.5~5","Lv.5~5"],"effect":["《조그레스: 옐로 Lv.5+퍼플 Lv.5에서 0》지정된 디지몬 2마리를 겹쳐 액티브로 진화시킨다. \n【진화 시】자신의 트래시에서 옐로 또는 퍼플인 디지몬 카드 1장을 자신의 시큐리티 위에 뒤집어서 놓는다. 조그레스 진화하고 있었을 때, 자신의 시큐리티를 모두 확인하여, 그중 Lv.5 이하의 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 그 후, 자신의 시큐리티를 셔플한다.\n 【서로의 턴】효과로 자신의 다른 디지몬이 등장했을 때, 등장한 디지몬의 Lv. 이하인 상대 디지몬 1마리를 소멸시킨다.","-","-"],"card_number":"ST10-06","card_level":"SR","image_link":"https://i.imgur.com/MDxb34b.png","LOCAL_NUMBER":16005},
{"name":"아이고스몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터종 고스트형","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【상대의 턴】옐로인 자신의 디지몬이 있는 동안, 이 디지몬은 《블로커》 (상대의 디지몬이 어택했을 때, 이 디지몬이 액티브 상태라면 레스트시키는 것으로 어택의 대상을 이 디지몬으로 한다)를 얻는다.","-","-"],"card_number":"ST10-07","card_level":"C","image_link":"https://i.imgur.com/w93tOZd.png","LOCAL_NUMBER":16006},
{"name":"츠카이몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스종 포유류형","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【등장 시】자신의 덱 위에서부터 3장 오픈한다. 그중 특징으로 「천사형」 또는 「대천사형」 또는 「타천사형」을 가진 카드 1장을 패에 추가한다. 남은 카드는 원하는 순서대로 덱 아래로 되돌린다.","-","-"],"card_number":"ST10-08","card_level":"U","image_link":"https://i.imgur.com/PpDLg0Q.png","LOCAL_NUMBER":16007},
{"name":"위치몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터종 마인형","dp":4000,"cost":6,"evolution_cost":["Lv.3~2","-"],"effect":["【시큐리티】배틀 종료 시, 이 카드를 코스트를 지불하지 않고 등장시킨다. \n【등장 시】자신의 트래시에서 퍼플인 Lv.5 이하의 디지몬 카드 1장을 패로 되돌린다.","-","-"],"card_number":"ST10-09","card_level":"U","image_link":"https://i.imgur.com/wp6f4at.png","LOCAL_NUMBER":16008},
{"name":"위자몬","color":"자황","level":4,"type":"디지몬","attribute":"성숙기 데이터종 마인형","dp":6000,"cost":5,"evolution_cost":["Lv.3~2","Lv.3~2"],"effect":["-","-","-"],"card_number":"ST10-10","card_level":"C","image_link":"https://i.imgur.com/E3osmxs.png","LOCAL_NUMBER":16009},
{"name":"바스테몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 바이러스종 수인형","dp":7000,"cost":6,"evolution_cost":["Lv.4~3","-"],"effect":["【등장 시】Lv.3인 상대의 디지몬 1마리를 소멸시킨다.","-","-"],"card_number":"ST10-11","card_level":"C","image_link":"https://i.imgur.com/lv83Icd.png","LOCAL_NUMBER":16010},
{"name":"레이디데블몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 바이러스종 타천사형","dp":6000,"cost":6,"evolution_cost":["Lv.4~3","Lv.4~3"],"effect":["【진화 시】자신의 패를 1장 파기하는 것으로, 자신의 덱 위에서부터 3장 오픈한다. 그중 특징으로 「천사형」 또는 「대천사형」 또는 「타천사형」을 가진 옐로와 퍼플의 카드 1장씩을 패에 추가한다. 남은 카드는 원하는 순서대로 덱 아래로 되돌린다.","-","【자신의 턴】옐로인 자신의 디지몬 전부는 《길동무》 (배틀에서 이 디지몬만이 소멸했을 때, 배틀한 상대의 디지몬을 소멸시킨다)를 얻는다."],"card_number":"ST10-12","card_level":"R","image_link":"https://i.imgur.com/yQITO4d.png","LOCAL_NUMBER":16011},
{"name":"유노몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스종 신인형,올림푸스 12신","dp":11000,"cost":11,"evolution_cost":["Lv.5~3","Lv.5~3"],"effect":["《길동무》 (배틀에서 이 디지몬만이 소멸했을 때, 배틀한 상대의 디지몬을 소멸시킨다) \n【진화 시】자신의 덱 위에서부터 3장 파기한다. 그 후, 자신의 트래시에서 디지몬 카드 1장을 패로 되돌린다.","-","-"],"card_number":"ST10-13","card_level":"U","image_link":"https://i.imgur.com/aWcLCuF.png","LOCAL_NUMBER":16012},
{"name":"카오스 디그레이드","color":"황자","type":"옵션","attribute":"- - -","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["【메인】상대 디지몬 1마리를 상대의 시큐리티의 위 또는 아래에 뒤집어서 놓는다. 그렇게 했을 때, 상대의 시큐리티를 위에서부터 1장 파기한다.","【시큐리티】 상대 디지몬 1마리를 상대의 시큐리티의 위 또는 아래에 뒤집어서 놓을 수 있다.","-"],"card_number":"ST10-14","card_level":"R","image_link":"https://i.imgur.com/HR9Zam0.png","LOCAL_NUMBER":16013},
{"name":"암흑파","color":"자","type":"옵션","attribute":"- - -","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["【메인】자신의 덱 위에서부터 3장 파기한다. 그 후, 옐로인 자신의 디지몬이 있을 때, 자신의 트래시에서 옐로 또는 퍼플의 디지몬 카드 1장을 패로 되돌린다.","【시큐리티】 이 카드의 【메인】 효과를 발휘한다.","-"],"card_number":"ST10-15","card_level":"U","image_link":"https://i.imgur.com/mdX0uDb.png","LOCAL_NUMBER":16014}]