
ST12=
[{"name":"구리몬","color":"적","level":2,"type":"디지타마","attribute":"유년기 - 렛서형","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【자신의 턴】자신의 디지몬이 2마리 이상 있는 동안, 이 디지몬을 DP+1000."],"card_number":"ST12-01","card_level":"U","image_link":"https://i.imgur.com/jhMUz6b.png","LOCAL_NUMBER":16200},
{"name":"캔들몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 데이터종 화염형","dp":3000,"cost":2,"evolution_cost":["Lv.2~0","-"],"effect":["-","-","-"],"card_number":"ST12-02","card_level":"C","image_link":"https://i.imgur.com/mCOrnbD.png","LOCAL_NUMBER":16201},
{"name":"황금톱니몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 백신종 머신형","dp":3000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【서로의 턴】서로는 지불하는 등장 코스트를 마이너스할 수 없다.","-","-"],"card_number":"ST12-03","card_level":"C","image_link":"https://i.imgur.com/mFE8lgX.png","LOCAL_NUMBER":16202},
{"name":"헉몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 데이터종 소룡형","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【자신의 턴】〔턴에 1회〕명칭에 「시스터몬」을 포함하는 자신의 디지몬이 등장했을 때, 메모리+1.","-","【서로의 턴】이 디지몬이 명칭에 「헉몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 동안, 이 디지몬을 DP+1000."],"card_number":"ST12-04","card_level":"R","image_link":"https://i.imgur.com/oMgqjsy.png","LOCAL_NUMBER":16203},
{"name":"메라몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 데이터종 화염형","dp":4000,"cost":4,"evolution_cost":["Lv.3~1","-"],"effect":["-","-","-"],"card_number":"ST12-05","card_level":"U","image_link":"https://i.imgur.com/b7cHv0v.png","LOCAL_NUMBER":16204},
{"name":"바오헉몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 데이터종 공룡형","dp":6000,"cost":5,"evolution_cost":["Lv.3~2","-"],"effect":["-","-","【서로의 턴】이 디지몬이 명칭에 「헉몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 동안, 이 디지몬을 DP+1000."],"card_number":"ST12-06","card_level":"C","image_link":"https://i.imgur.com/cyUcDGk.png","LOCAL_NUMBER":16205},
{"name":"데드메라몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 데이터종 화염형","dp":9000,"cost":6,"evolution_cost":["Lv.4~3","-"],"effect":["-","-","-"],"card_number":"ST12-07","card_level":"C","image_link":"https://i.imgur.com/7e1UYDp.png","LOCAL_NUMBER":16206},
{"name":"세이버헉몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 데이터종 용인형","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【진화 시】이 턴 동안 이 디지몬은 액티브 상태의 상대 디지몬에게도 어택할 수 있다.","-","【어택 시】〔턴에 1회〕이 디지몬이 특징으로 「로얄 나이츠」를 가질 때, 자신의 패 또는 트래시에서 명칭에 「시스터몬」을 포함하는 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다."],"card_number":"ST12-08","card_level":"R","image_link":"https://i.imgur.com/lXA8hVw.png","LOCAL_NUMBER":16207},
{"name":"볼케몬","color":"적흑","level":5,"type":"디지몬","attribute":"완전체 데이터종 사이보그형","dp":9000,"cost":8,"evolution_cost":["Lv.4~4","Lv.4~4"],"effect":["《블로커》 (상대의 디지몬이 어택했을 때, 이 디지몬을 레스트시키는 것으로 어택의 대상을 이 디지몬으로 한다)","-","《시큐리티 어택 +1》 (이 디지몬이 체크하는 매수 +1)"],"card_number":"ST12-09","card_level":"U","image_link":"https://i.imgur.com/knkZ0lT.png","LOCAL_NUMBER":16208},
{"name":"제스몬","color":"적","level":6,"type":"디지몬","attribute":"궁극체 데이터종 성기사형,로얄 나이츠","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["【진화 시】《진격》(메모리가 상대측 1 이상일 때, 이 디지몬은 어택할 수 있다) 【어택 시】자신의 패에서, 명칭에 「시스터몬」을 포함하는 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 【자신의 턴】〔턴에 1회〕효과로 자신의 다른 디지몬이 등장했을 때, 이 턴 동안 이 디지몬을 DP+3000 하고, 《시큐리티 어택 +1》 (이 디지몬이 체크하는 매수 +1)을 얻는다.","-","-"],"card_number":"ST12-10","card_level":"SR","image_link":"https://i.imgur.com/zMf4yho.png","LOCAL_NUMBER":16209},
{"name":"간쿠몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 데이터종 성기사형,로얄 나이츠","dp":11000,"cost":12,"evolution_cost":["Lv.5~3","Lv.5~3"],"effect":["【진화 시】자신의 트래시에서 「헉몬」 또는 명칭에 「시스터몬」을 포함하는 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 【자신의 턴】〔턴에 1회〕효과로 자신의 다른 디지몬이 등장했을 때, 상대의 디지몬 2마리까지를 《퇴화 1》 (상대 디지몬 위에 포개진 카드를 위에서부터 1장 파기한다. 진화원이 없어지거나, Lv.3의 디지몬이 되었다면 그 이상 파기할 수 없다).","-","-"],"card_number":"ST12-11","card_level":"SR","image_link":"https://i.imgur.com/8mNf37j.png","LOCAL_NUMBER":16210},
{"name":"시스터몬 블랑","color":"백","level":3,"type":"디지몬","attribute":"성장기 백신종 퍼펫형","dp":3000,"cost":3,"evolution_cost":["-","-"],"effect":["【등장 시】자신의 패를 1장 파기하는 것으로 《2 드로우》 (자신의 덱에서 카드를 2장 드로우한다). 【서로의 턴】명칭에 「헉몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 자신의 디지몬이 있는 동안, 이 디지몬은 ≪디코이《레드/블랙》≫(레드 또는 블랙인 자신의 다른 디지몬이 상대의 효과로 소멸할 때, 이 디지몬을 소멸시키는 것으로, 그중 레드 또는 블랙인 디지몬 1마리는 소멸하지 않는다)을 얻는다.","-","-"],"card_number":"ST12-12","card_level":"U","image_link":"https://i.imgur.com/vbVQmcv.png","LOCAL_NUMBER":16211},
{"name":"시스터몬 느와르","color":"백","level":4,"type":"디지몬","attribute":"성숙기 바이러스종 퍼펫형","dp":5000,"cost":4,"evolution_cost":["-","-"],"effect":["【등장 시】자신의 덱 위에서부터 3장 오픈한다. 그중 명칭에 「헉몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 카드 1장을 패에 추가한다. 나머지는 파기한다. 【서로의 턴】명칭에 「헉몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 자신의 디지몬 전부는 《재기동》 (상대의 액티브 페이즈에, 이 디지몬을 액티브로 한다)을 얻는다. ※명칭: 「시스터몬 시엘」, 특징: 「데이터종」으로도 취급한다.","-","-"],"card_number":"ST12-13","card_level":"U","image_link":"https://i.imgur.com/IbrUOpN.png","LOCAL_NUMBER":16212},
{"name":"아우스 제네릭스","color":"적","level":"-","type":"옵션","attribute":"- - -","dp":"-","cost":1,"evolution_cost":["-","-"],"effect":["【메인】이 턴 동안 자신의 디지몬 1마리를 DP+2000. 그 후, 명칭에 「헉몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 자신의 디지몬이 있을 때, 메모리+1 하고, 이 턴 동안 자신의 디지몬 1마리는 《관통》 (이 디지몬이 어택한 배틀에서 상대의 디지몬을 소멸시켰을 때, 어택 종료 전에 체크한다)을 얻는다.","【시큐리티】메모리+1 하고, 이 카드를 패에 추가한다.","-"],"card_number":"ST12-14","card_level":"C","image_link":"https://i.imgur.com/TAtlwMp.png","LOCAL_NUMBER":16213},
{"name":"사제의 여행길","color":"적","level":"-","type":"옵션","attribute":"- 로얄 나이츠 -","dp":"-","cost":2,"evolution_cost":["-","-"],"effect":["【메인】자신의 덱 위에서부터 3장 오픈한다. 그중 명칭에 「헉몬」 또는 「시스터몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 카드 1장을 패에 추가한다. 나머지는 파기한다. 그 후, 이 카드를 배틀 에어리어에 놓는다. 【메인】《딜레이》(배틀 에어리어에 있는 이 카드를 파기하는 것으로, 이하의 효과를 발휘한다. 이 효과는 이 카드를 놓은 턴에는 발휘할 수 없다) ・이 턴 동안 다음에 자신의 디지몬이 진화할 때, 지불하는 진화 코스트-1.","【시큐리티】자신의 덱 위에서부터 3장 오픈한다. 그중 명칭에 「헉몬」 또는 「시스터몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 카드 1장을 패에 추가한다. 나머지는 파기한다. 그 후, 이 카드를 배틀 에어리어에 놓는다.","-"],"card_number":"ST12-15","card_level":"C","image_link":"https://i.imgur.com/CdU4LpT.png","LOCAL_NUMBER":16214},
{"name":"지진! 천둥! 화재! 아버지!","color":"흑","level":"-","type":"옵션","attribute":"- - -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["명칭에 「헉몬」 또는 「시스터몬」을 포함하거나 특징으로 「로얄 나이츠」를 가진 자신의 디지몬이 있는 동안, 이 카드는 색 조건을 무시하고 사용할 수 있다. 【메인】등장 코스트 13 이하의 상대 디지몬 1마리를 소멸시킨다.","【시큐리티】이 카드의 【메인】효과를 발휘한다.","-"],"card_number":"ST12-16","card_level":"R","image_link":"https://i.imgur.com/xH3Ed3v.png","LOCAL_NUMBER":16215}]

ST13=
[{"name":"사쿳토몬","color":"흑","level":2,"type":"디지타마","attribute":"유년기 - 무기형","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【자신의 턴】〔턴에 1회〕효과로 특징으로 「Legend-Arms」를 가진 자신의 다른 디지몬이 등장했을 때, 메모리+1."],"card_number":"ST13-01","card_level":"U","image_link":"https://i.imgur.com/9xKGVd2.png","LOCAL_NUMBER":16216},
{"name":"즈바몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 백신종 무기형,Legend-Arms","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【등장 시】이 디지몬을 특징으로 「Legend-Arms」를 가지거나 블랙인 자신의 다른 디지몬 1마리의 진화원 아래에 놓는 것으로, 자신의 덱 위에서부터 1장 오픈한다. 그 카드가 특징으로 「Legend-Arms」를 가진 등장 코스트 7 이하의 디지몬 카드라면 코스트를 지불하지 않고 등장시킬 수 있다. 남은 카드는 패에 추가한다.","-","【어택 시】특징으로 「Legend-Arms」를 가지거나 블랙인 자신의 디지몬이 있을 때, DP 3000 이하의 상대 디지몬 1마리를 소멸시킨다."],"card_number":"ST13-02","card_level":"U","image_link":"https://i.imgur.com/LZggVfs.png","LOCAL_NUMBER":16217},
{"name":"즈바이거몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 백신종 무기형,Legend-Arms","dp":4000,"cost":5,"evolution_cost":["Lv.3~2","Lv.3~2"],"effect":["【등장 시】이 디지몬을 특징으로 「Legend-Arms」를 가지거나 블랙인 자신의 다른 디지몬 1마리의 진화원 아래에 놓는 것으로, DP 5000 이하의 상대 디지몬 1마리를 소멸시킨다.","-","【어택 시】특징으로 「Legend-Arms」를 가지거나 블랙인 자신의 디지몬이 있을 때, DP 3000 이하의 상대 디지몬 1마리를 소멸시킨다."],"card_number":"ST13-03","card_level":"C","image_link":"https://i.imgur.com/BB4qFD3.png","LOCAL_NUMBER":16218},
{"name":"듀라몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 백신종 무기형,Legend-Arms","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","Lv.4~3"],"effect":["【자신의 턴】이 디지몬이 패의 특징으로 「Legend-Arms」를 가진 카드나 블랙인 카드로 진화할 때, 지불하는 진화 코스트-1.","-","【자신의 턴 종료 시】이 디지몬과 자신의 다른 디지몬으로, 코스트를 지불하여 패의 디지몬 카드로 조그레스 진화할 수 있다."],"card_number":"ST13-04","card_level":"U","image_link":"https://i.imgur.com/LkfpC3q.png","LOCAL_NUMBER":16219},
{"name":"듀란다몬","color":"적","level":6,"type":"디지몬","attribute":"궁극체 백신종 성검형,Legend-Arms","dp":11000,"cost":11,"evolution_cost":["Lv.5~3","Lv.5~3"],"effect":["【자신의 턴】〔턴에 1회〕자신의 효과로 이 디지몬의 진화원이 늘어났을 때, 이 턴 동안 이 디지몬을 DP+3000 하고, 《시큐리티 어택 +1》 (이 디지몬이 체크하는 매수 +1)을 얻는다. 【어택 시】자신의 덱 위에서부터 3장 오픈한다. 그중 특징으로 「Legend-Arms」를 가진 등장 코스트 7 이하의 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 나머지는 원하는 순서대로 덱 아래로 되돌린다.","-","【자신의 턴】이 디지몬이 「라그나로드몬」인 동안, 이 디지몬이 체크한 옵션 카드의 【시큐리티】효과는 발휘하지 않는다."],"card_number":"ST13-05","card_level":"SR","image_link":"https://i.imgur.com/Pc03wFg.png","LOCAL_NUMBER":16220},
{"name":"라그나로드몬","color":"적흑","level":7,"type":"디지몬","attribute":"궁극체 바이러스종 특이형,Legend-Arms","dp":15000,"cost":15,"evolution_cost":["Lv.6~6","Lv.6~6"],"effect":["조그레스: 레드 Lv.6+블랙 Lv.6에서 0【진화 시】《진격》(메모리가 상대측 1 이상일 때, 이 디지몬은 어택할 수 있다). 조그레스 진화하고 있었을 때, 이 디지몬의 진화원 4장마다 등장 코스트 20 이하의 상대 디지몬 1마리를 소멸시키고, 상대의 시큐리티를 위에서부터 1장 파기한다. 【서로의 턴】〔턴에 1회〕자신 또는 상대의 시큐리티가 줄어들었을 때, 이 디지몬을 액티브로 한다.","-","-"],"card_number":"ST13-06","card_level":"SR","image_link":"https://i.imgur.com/QNxjGZV.png","LOCAL_NUMBER":16221},
{"name":"코테몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 데이터종 파충류형","dp":3000,"cost":2,"evolution_cost":["Lv.2~0","-"],"effect":["-","-","-"],"card_number":"ST13-07","card_level":"C","image_link":"https://i.imgur.com/2i09rqc.png","LOCAL_NUMBER":16222},
{"name":"치쿠리몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 바이러스종 기뢰형","dp":3000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【서로의 턴】서로는 지불하는 등장 코스트를 마이너스할 수 없다.","-","-"],"card_number":"ST13-08","card_level":"C","image_link":"https://i.imgur.com/55VSnQi.png","LOCAL_NUMBER":16223},
{"name":"루도몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 데이터종 방어구형,Legend-Arms","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【등장 시】이 디지몬을 특징으로 「Legend-Arms」를 가지거나 레드인 자신의 다른 디지몬 1마리의 진화원 아래에 놓는 것으로, 자신의 덱 위에서부터 1장 오픈한다. 그 카드가 특징으로 「Legend-Arms」를 가진 등장 코스트 7 이하의 디지몬 카드라면 코스트를 지불하지 않고 등장시킬 수 있다. 남은 카드는 패에 추가한다.","-","【상대의 턴】특징으로 「Legend-Arms」를 가지거나 레드인 자신의 디지몬이 있는 동안, 이 디지몬은 《블로커》 (상대의 디지몬이 어택했을 때, 이 디지몬을 레스트시키는 것으로 어택의 대상을 이 디지몬으로 한다)를 얻는다."],"card_number":"ST13-09","card_level":"U","image_link":"https://i.imgur.com/MySIz30.png","LOCAL_NUMBER":16224},
{"name":"그라디몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 백신종 전사형","dp":4000,"cost":4,"evolution_cost":["Lv.3~1","-"],"effect":["-","-","-"],"card_number":"ST13-10","card_level":"C","image_link":"https://i.imgur.com/iHiGzWg.png","LOCAL_NUMBER":16225},
{"name":"티아루도몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 데이터종 방어구형,Legend-Arms","dp":4000,"cost":5,"evolution_cost":["Lv.3~2","Lv.3~2"],"effect":["【등장 시】이 디지몬을 특징으로 「Legend-Arms」를 가지거나 레드인 자신의 다른 디지몬 1마리의 진화원 아래에 놓는 것으로, 다음 상대의 턴 종료까지 자신의 디지몬 1마리는 《재기동》 (상대의 액티브 페이즈에, 이 디지몬을 액티브로 한다)을 얻는다.","-","【상대의 턴】특징으로 「Legend-Arms」를 가지거나 레드인 자신의 디지몬이 있는 동안, 이 디지몬은 《블로커》 (상대의 디지몬이 어택했을 때, 이 디지몬을 레스트시키는 것으로 어택의 대상을 이 디지몬으로 한다)를 얻는다."],"card_number":"ST13-11","card_level":"U","image_link":"https://i.imgur.com/lKZA5hA.png","LOCAL_NUMBER":16226},
{"name":"나이트몬","color":"흑적","level":5,"type":"디지몬","attribute":"완전체 데이터종 전사형","dp":7000,"cost":5,"evolution_cost":["Lv.4~3","Lv.4~3"],"effect":["-","-","-"],"card_number":"ST13-12","card_level":"C","image_link":"https://i.imgur.com/ScwVxqC.png","LOCAL_NUMBER":16227},
{"name":"라이지루도몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 데이터종 방어구형,Legend-Arms","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","Lv.4~3"],"effect":["【상대의 턴】이 디지몬은 상대의 효과로는 소멸하지 않는다.","-","【자신의 턴 종료 시】이 디지몬과 자신의 다른 디지몬으로, 코스트를 지불하여 패의 디지몬 카드로 조그레스 진화할 수 있다."],"card_number":"ST13-13","card_level":"R","image_link":"https://i.imgur.com/4wrxyjF.png","LOCAL_NUMBER":16228},
{"name":"브리웨루드라몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 데이터종 방어구형,Legend-Arms","dp":12000,"cost":11,"evolution_cost":["Lv.5~4","Lv.5~4"],"effect":["【자신의 턴】〔턴에 1회〕자신의 효과로 이 디지몬의 진화원이 늘어났을 때, 다음 상대의 턴 종료까지 이 디지몬은 상대의 효과로 소멸하지 않으며, 패 및 덱으로 돌아가지 않는다. 【진화 시】자신의 덱 위에서부터 3장 오픈한다. 그중 특징으로 「Legend-Arms」를 가진 등장 코스트 7 이하의 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 나머지는 원하는 순서대로 덱 아래로 되돌린다.","-","【상대의 턴】이 디지몬이 「라그나로드몬」인 동안, 이 디지몬은 상대 디지몬의 효과를 받지 않는다."],"card_number":"ST13-14","card_level":"R","image_link":"https://i.imgur.com/E3O6kRt.png","LOCAL_NUMBER":16229},
{"name":"다이렉트 스매셔","color":"적","level":"-","type":"옵션","attribute":"- - -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["특징으로 「Legend-Arms」를 가진 자신의 디지몬이 있는 동안, 이 카드는 색 조건을 무시하고 사용할 수 있다. 【메인】가장 DP가 높은 상대의 디지몬 1마리를 소멸시킨다.","【시큐리티】이 카드의 【메인】 효과를 발휘한다.","-"],"card_number":"ST13-15","card_level":"R","image_link":"https://i.imgur.com/fsqQwg7.png","LOCAL_NUMBER":16230},
{"name":"모순공투","color":"흑적","level":"-","type":"옵션","attribute":"- - -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["【메인】자신의 패에서 특징으로 「Legend-Arms」를 가진 등장 코스트 7 이하의 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 그 후, 이 카드를 배틀 에어리어에 놓는다. 【메인】《딜레이》(배틀 에어리어에 있는 이 카드를 파기하는 것으로, 이하의 효과를 발휘한다. 이 효과는 이 카드를 놓은 턴에는 발휘할 수 없다) ・자신의 덱 위에서부터 4장 오픈한다. 오픈한 카드는 원하는 순서대로 덱 위 또는 아래로만 되돌린다.","【시큐리티】자신의 패에서 특징으로 「Legend-Arms」를 가진 등장 코스트 7 이하의 디지몬 카드 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 그 후, 이 카드를 배틀 에어리어에 놓는다.","-"],"card_number":"ST13-16","card_level":"C","image_link":"https://i.imgur.com/UpmJki0.png","LOCAL_NUMBER":16231}]



ST14=
[{"name":"임프몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스종 소악마형","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【어택 시】자신의 트래시가 20장 이상이라면, 이 디지몬을 자신의 트래시의 「베르제브몬」으로 진화조건을 무시하고 진화 코스트 3으로 진화시킬 수 있다.","-","【자신의 턴】[턴에 1회]자신의 덱이 파기되었을 때, Lv.3의 상대의 디지몬 1마리를 소멸시킨다."],"card_number":"ST14-02","card_level":"SR","image_link":"https://i.imgur.com/tQzFvNV.png"},
{"name":"야몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - 렛서형","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【어택 시】[턴에 1회]이 디지몬이 특징으로 「마인형」/「마왕형」을 가진다면, 자신의 덱 위에서부터 2장 파기한다."],"card_number":"ST14-01","card_level":"U","image_link":"https://i.imgur.com/6M0ldpa.png"},
{"name":"캔들몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터종 화염형","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【등장 시】자신의 덱 위에서부터 2장 파기한다. 【소멸 시】자신의 트래시가 10장 이상이라면 , 《1 드로우》(자신의 덱에서 카드를 1장 뽑는다).","-","-"],"card_number":"ST14-03","card_level":"U","image_link":"https://i.imgur.com/4MmtMWr.png"},
{"name":"파스코몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스종 마수형","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["《블로커》(이 디지몬은 블록 타이밍에 블록할 수 있다) 【자신의 턴】이 디지몬은 플레이어에게 어택할 수 없다.","-","-"],"card_number":"ST14-04","card_level":"C","image_link":"https://i.imgur.com/jPkP6dl.png"},
{"name":"포큐파몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스종 퍼펫형","dp":4000,"cost":4,"evolution_cost":["Lv.3~2","-"],"effect":["《블로커》(이 디지몬은 블록 타이밍에 블록할 수 있다) 【등장 시】자신의 덱 위에서부터 2장 파기한다.","-","-"],"card_number":"ST14-05","card_level":"C","image_link":"https://i.imgur.com/dyDynKA.png"},
{"name":"위치몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터종 마인형","dp":5000,"cost":5,"evolution_cost":["Lv.3~2","-"],"effect":["【진화 시】자신의 덱 위에서부터 3장 파기한다.","-","【자신의 턴】특징으로 「마인형」/「마왕형」을 가진 이 디지몬을 DP +2000."],"card_number":"ST14-06","card_level":"U","image_link":"https://i.imgur.com/x3UI3kB.png"},
{"name":"바알몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 프리 마인형","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【진화 시】자신의 덱 위에서부터 3장 파기한다. 【진화 시】상대의 턴 종료까지 이 디지몬은 「【소멸 시】자신의 트래시가 10장 이상이라면, 자신의 트래시에서 「베르제브몬」 1장을 코스트를 지불하지 않고 등장시킬 수 있다.」의 효과를 얻는다.","-","【자신의 턴】특징으로 「마인형」/「마왕형」을 가진 이 디지몬을 DP +2000."],"card_number":"ST14-07","card_level":"R","image_link":"https://i.imgur.com/t8tUIZW.png"},
{"name":"베르제브몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스종 마왕형,7대마왕","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["【진화 시】자신의 덱 위에서부터 4장 파기한다. 【서로의 턴】[턴에 1회]자신의 덱이 파기되었을 때, 자신의 트래시 10장마다, 메모리 +1. 【자신의 턴】[턴에 1회]자신의 덱이 파기되었을 때, 턴 종료까지 이 디지몬은 《S 어택 +1》(이 디지몬이 체크하는 매수 +1)을 얻는다.","-","-"],"card_number":"ST14-08","card_level":"SR","image_link":"https://i.imgur.com/AAXOERb.png"},
{"name":"베르스타몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스종 마인형,3총사","dp":11000,"cost":13,"evolution_cost":["Lv.5~3","-"],"effect":["패의 이 카드가 등장할 때, 자신의 트래시 10장마다 지불하는 등장 코스트 -4. 【서로의 턴】[턴에 1회]자신의 덱이 파기되었을 때, 자신의 트래시에서 「임프몬」 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 턴 종료까지 이 효과로 등장한 디지몬은 《속공》을 얻는다. 【상대의 턴】상대의 디지몬이 어택했을 때, 자신의 덱 위에서부터 1장 파기한다.","-","-"],"card_number":"ST14-09","card_level":"SR","image_link":"https://i.imgur.com/0fTI9Pw.png"},
{"name":"베르제브몬: 블래스트 모드","color":"자","level":7,"type":"디지몬","attribute":"궁극체 바이러스종 마왕형","dp":14000,"cost":14,"evolution_cost":["Lv.6~4","-"],"effect":["이 카드가 덱에서 파기되었을 때, Lv.3 이하의 상대의 디지몬 1마리를 소멸시킨다. 자신의 트래시 10장마다 이 효과로 선택할 수 있는 Lv. 상한 +1. 【진화 시】이 디지몬을 액티브로 한다. 자신의 트래시가 20장 이상이라면, 메모리 +3.","-","-"],"card_number":"ST14-10","card_level":"SR","image_link":"https://i.imgur.com/mWbnToO.png"},
{"name":"다영&진","color":"자","level":"-","type":"테이머","attribute":"- - -","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["【등장 시】자신의 덱 위에서부터 4장 오픈한다. 그중 특징으로 「소악마형」/「마인형」/「마왕형」을 가진 디지몬 카드 1장을 패에 추가한다. 나머지는 덱 아래로 되돌린다. 【자신의 턴】자신의 디지몬이 퍼플인 디지몬으로 진화했을 때, 이 테이머를 레스트시키는 것으로, 자신의 패 1장을 덱 위로 되돌리고, 메모리 +1.","【시큐리티】이 카드를 코스트를 지불하지 않고 등장시킨다.","-"],"card_number":"ST14-11","card_level":"R","image_link":"https://i.imgur.com/fywvJWS.png"},
{"name":"견원의 흉탄","color":"자","level":"-","type":"옵션","attribute":"- - -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["이 카드가 덱에서 파기되었을 때, 이 카드를 배틀 에어리어에 놓을 수 있다. 【메인】가장 Lv.이 높은 상대의 디지몬 1마리를 소멸시킨다. 【메인】《딜레이》(놓인 다음 턴 이후에 이 카드를 파기하는 것으로, 효과를 발휘한다) ・자신의 트래시에서 퍼플인 디지몬 카드/테이머 카드 1장을 패로 되돌린다.","【시큐리티】가장 Lv.이 높은 상대의 디지몬 1마리를 소멸시킨다.","-"],"card_number":"ST14-12","card_level":"R","image_link":"https://i.imgur.com/Byc61OS.png"},
]

ST15=[
{"name":"코로몬","color":"흑","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST15-01","card_level":"U","image_link":"https://i.imgur.com/swxQ1g6.png","LOCAL_NUMBER":16244},
{"name":"아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Reptile","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[Digivolve][Koromon]: Cost 0[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.","-","-"],"card_number":"ST15-02","card_level":"R","image_link":"https://i.imgur.com/dKh8VPd.png","LOCAL_NUMBER":16245},
{"name":"투명아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["-","-","-"],"card_number":"ST15-03","card_level":"U","image_link":"https://i.imgur.com/Q1WJCmk.png","LOCAL_NUMBER":16246},
{"name":"솔라몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Machine","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[On Play] Reveal the top card of your deck. If it's a black card, add it to your hand. Trash the rest.","-","-"],"card_number":"ST15-04","card_level":"C","image_link":"https://i.imgur.com/qMzljxS.png","LOCAL_NUMBER":16247},
{"name":"토이아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","dp":4000,"cost":4,"evolution_cost":["Lv.1~2","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.) [Your Turn] When this Digimon attacks a player, lose 2 memory.","-","-"],"card_number":"ST15-05","card_level":"C","image_link":"https://i.imgur.com/Cfx2Aye.png","LOCAL_NUMBER":16248},
{"name":"메카노몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Machine","dp":5000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["-","-","-"],"card_number":"ST15-06","card_level":"C","image_link":"https://i.imgur.com/XPxgXXs.png","LOCAL_NUMBER":16249},
{"name":"탱크몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 데이터 Cyborg","dp":6000,"cost":5,"evolution_cost":["Lv.2~3","-"],"effect":["＜Jamming＞ (This Digimon can't be deleted in battles against Security Digimon.)","-","-"],"card_number":"ST15-07","card_level":"C","image_link":"https://i.imgur.com/9laXQIr.png","LOCAL_NUMBER":16250},
{"name":"그레이몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Dinosaur","dp":5000,"cost":6,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] Lv.3 w/[Agumon] in name: Cost 2[Security] You may play 1 [Agumon] or 1 Tamer card with [Tai Kamiya] in its name from your hand or trash without paying the cost. ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST15-08","card_level":"SR","image_link":"https://i.imgur.com/LvD0TXc.png","LOCAL_NUMBER":16251},
{"name":"나이트몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Warrior","dp":7000,"cost":6,"evolution_cost":["Lv.3~4","-"],"effect":["[On Play] Delete 1 of your opponent's Digimon with a play cost of 5 or less.","-","-"],"card_number":"ST15-09","card_level":"C","image_link":"https://i.imgur.com/KBl5Xul.png","LOCAL_NUMBER":16252},
{"name":"안드로몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","-"],"effect":["[When Digivolving] ＜De-Digivolve 1＞ 1 of your opponent's Digimon. (Trash the top card. You can't trash past level 3 cards.)","-","-"],"card_number":"ST15-10","card_level":"U","image_link":"https://i.imgur.com/trJhLV9.png","LOCAL_NUMBER":16253},
{"name":"메탈그레이몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","dp":8000,"cost":8,"evolution_cost":["Lv.3~4","-"],"effect":["[Digivolve] Lv.4 w/[Greymon] in name: Cost 3＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST15-11","card_level":"R","image_link":"https://i.imgur.com/1ZYs7bC.png","LOCAL_NUMBER":16254},
{"name":"워그레이몬 ACE","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Dragonkin","dp":11000,"cost":6,"evolution_cost":["Lv.4~5","-"],"effect":["[Digivolve] Lv.5 w/[Greymon] in name: Cost 3[Hand][Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) ＜Blocker＞ [All Turns][Once Per Turn] When a card is removed from a security stack, you may unsuspend this Digimon.","-","-"],"card_number":"ST15-12","card_level":"SR","image_link":"https://i.imgur.com/pu1vGv2.png","LOCAL_NUMBER":16255},
{"name":"하이안드로몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Cyborg","dp":12000,"cost":11,"evolution_cost":["Lv.4~5","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target. [When Digivolving] Delete 1 of your opponent's Digimon with a play cost of 8 or less.","-","-"],"card_number":"ST15-13","card_level":"U","image_link":"https://i.imgur.com/Za3uH9G.png","LOCAL_NUMBER":16256},
{"name":"신태일","color":"흑","type":"테이머","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Start of Your Turn] If you have 2 or fewer memory, set it to 3. [All Turns] When an attack target is switched, by suspending this Tamer, ＜Draw 1＞ and 1 of your Digimon gets +2000 DP until the end of the turn.","-","-"],"card_number":"ST15-14","card_level":"R","image_link":"https://i.imgur.com/2wk3OgR.png","LOCAL_NUMBER":16257},
{"name":"용기의전진","color":"흑","type":"Opiton","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["While you have a Tamer with [Tai Kamiya] in its name, you may use this card without meeting its color requirements. [Main] Unsuspend 1 of your Digimon. Then, 1 of your Digimon with [Greymon] in its name isn't affected by the effects of your opponent's Digimon until the end of your opponent's turn.","-","-"],"card_number":"ST15-15","card_level":"U","image_link":"https://i.imgur.com/1oKOs1x.png","LOCAL_NUMBER":16258},
{"name":"트라이던트 암","color":"흑","type":"Opiton","attribute":"- -","dp":"-","cost":6,"evolution_cost":["-","-"],"effect":["[Main] ＜De-Digivolve 3＞ 1 of your opponent's Digimon. Then, until the end of your opponent's turn, 1 of your opponent's Digimon gains \"[Start of Your Main Phase] This Digimon attacks.\"","-","-"],"card_number":"ST15-16","card_level":"C","image_link":"https://i.imgur.com/wtR18Df.png","LOCAL_NUMBER":16259}]

ST16=[
{"name":"뿔몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST16-01","card_level":"U","image_link":"https://i.imgur.com/sIssMqX.png","LOCAL_NUMBER":16260},
{"name":"에렉몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Mammal","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[On Play] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand.","-","-"],"card_number":"ST16-02","card_level":"C","image_link":"https://i.imgur.com/3BIC5z0.png","LOCAL_NUMBER":16261},
{"name":"파피몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Reptile","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[Digivolve] [Tsunomon]: Cost 0[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.","-","-"],"card_number":"ST16-03","card_level":"R","image_link":"https://i.imgur.com/5pY8WIv.png","LOCAL_NUMBER":16262},
{"name":"테이파몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 백신 Holy Beast","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["-","-","-"],"card_number":"ST16-04","card_level":"U","image_link":"https://i.imgur.com/sum9n2f.png","LOCAL_NUMBER":16263},
{"name":"울퉁몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Rock","dp":4000,"cost":4,"evolution_cost":["Lv.1~2","-"],"effect":["＜Retaliation＞ (When this Digimon is deleted in battle, delete the Digimon it battled.) [Your Turn] When this Digimon attacks an opponent's Digimon, lose 2 memory.","-","-"],"card_number":"ST16-05","card_level":"C","image_link":"https://i.imgur.com/zTFxLsj.png","LOCAL_NUMBER":16264},
{"name":"고스몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Ghost","dp":5000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST16-06","card_level":"C","image_link":"https://i.imgur.com/UdooJtO.png","LOCAL_NUMBER":16265},
{"name":"메라몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터 Flame","dp":6000,"cost":5,"evolution_cost":["Lv.2~3","-"],"effect":["[On Deletion] Gain 1 memory.","-","-"],"card_number":"ST16-07","card_level":"C","image_link":"https://i.imgur.com/KuJw6Hh.png","LOCAL_NUMBER":16266},
{"name":"가루몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 백신 Beast","dp":5000,"cost":6,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] Lv.3 w/[Gabumon] in name: Cost 2[Security] You may play 1 [Gabumon] or 1 Tamer card with [Matt Ishida] in its name from your hand or trash without paying the cost. [When Digivolving] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand.","-","-"],"card_number":"ST16-08","card_level":"SR","image_link":"https://i.imgur.com/ppsDxW1.png","LOCAL_NUMBER":16267},
{"name":"펌프몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 데이터 Puppet","dp":7000,"cost":6,"evolution_cost":["Lv.3~4","-"],"effect":["[On Play] You may play 1 purple level 3 Digimon card from your trash without paying the cost.","-","-"],"card_number":"ST16-09","card_level":"C","image_link":"https://i.imgur.com/WxMkikf.png","LOCAL_NUMBER":16268},
{"name":"맘몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 백신 Ancient Animal","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST16-10","card_level":"U","image_link":"https://i.imgur.com/219j0x9.png","LOCAL_NUMBER":16269},
{"name":"워가루몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 백신 Beastkin","dp":8000,"cost":8,"evolution_cost":["Lv.3~4","-"],"effect":["[Digivolve] Lv.4 w/[Garurumon] in name: Cost 3[When Attacking][Once Per Turn] By trashing 1 card in your hand, unsuspend this Digimon.","-","-"],"card_number":"ST16-11","card_level":"R","image_link":"https://i.imgur.com/RggzBH8.png","LOCAL_NUMBER":16270},
{"name":"메탈가루몬 ACE","color":"자","level":6,"type":"디지몬","attribute":"궁극체 데이터 Cyborg","dp":11000,"cost":6,"evolution_cost":["Lv.4~5","-"],"effect":["[Digivolve] Lv.5 w/[Garurumon] in name: Cost 3[Hand][Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) [When Digivolving] By trashing up to 3 cards in your hand, gain 1 memory for each card trashed. [When Attacking][Once Per Turn] By trashing 1 card in your hand, delete 1 of your opponent's Digimon with the lowest level.","-","-"],"card_number":"ST16-12","card_level":"SR","image_link":"https://i.imgur.com/dMm4dGI.png","LOCAL_NUMBER":16271},
{"name":"스컬맘몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 백신 Undead","dp":12000,"cost":11,"evolution_cost":["Lv.4~5","-"],"effect":["[When Digivolving] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand. [All Turns][Once Per Turn] When one of your effects trashes a card in your hand, you may play 1 level 4 or lower purple Digimon card from your trash without paying the cost.","-","-"],"card_number":"ST16-13","card_level":"U","image_link":"https://i.imgur.com/subkrCo.png","LOCAL_NUMBER":16272},
{"name":"매튜","color":"자","type":"테이머","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Start of Your Turn] If you have 2 or fewer memory, set it to 3. [All Turns] When one of your effects trashes a card in your hand, by suspending this Tamer, gain 1 memory.","-","-"],"card_number":"ST16-14","card_level":"R","image_link":"https://i.imgur.com/f9QtrQK.png","LOCAL_NUMBER":16273},
{"name":"우정의통곡","color":"자","type":"Opiton","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["While you have a Tamer with [Matt Ishida] in its name, you may use this card without meeting its color requirements.[Main] Return 1 Digimon card from your trash to the hand. Then, 1 of your Digimon with [Garurumon] in its name gains \"[On Deletion] Play this card without paying the cost\" until the end of your opponent's turn.","-","-"],"card_number":"ST16-15","card_level":"U","image_link":"https://i.imgur.com/fXulq8J.png","LOCAL_NUMBER":16274},
{"name":"볼 디블로","color":"자","type":"Opiton","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Main] Delete 1 of your opponent's level 5 or lower Digimon.","-","-"],"card_number":"ST16-16","card_level":"C","image_link":"https://i.imgur.com/GEpPTdj.png","LOCAL_NUMBER":16275}]

ST17=[
{"name":"구미몬","color":"녹","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST17-01","card_level":"U","image_link":"https://i.imgur.com/dfgiyfG.png","LOCAL_NUMBER":16276},
{"name":"테리어몬","color":"녹","level":3,"type":"디지몬","attribute":"성장기 백신 Beast","dp":1000,"cost":3,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] [Gummymon]: Cost 0[Main] [Once Per Turn] You may play 1 green Tamer card or 1 level 3 Digimon card with [Lopmon] in its name from your hand with the play cost reduced by 2.","-","-"],"card_number":"ST17-02","card_level":"SR","image_link":"https://i.imgur.com/CX96kpV.png","LOCAL_NUMBER":16277},
{"name":"로프몬","color":"녹","level":3,"type":"디지몬","attribute":"성장기 데이터 Beast","dp":1000,"cost":3,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] [Kokomon]: Cost 0[Main] [Once Per Turn] 1 of your Digimon gains ＜Alliance＞ for the turn.","-","-"],"card_number":"ST17-03","card_level":"SR","image_link":"https://i.imgur.com/OErKVHJ.png","LOCAL_NUMBER":16278},
{"name":"웬디몬","color":"녹자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Beastkin","dp":4000,"cost":5,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] Lv.3 w/[Terriermon]/[Lopmon] in name: Cost 2[On Play] [When Digivolving] Delete 1 level 3 or lower Digimon. If this effect deleted one of your Digimon, you may play 1 level 3 Digimon card with [Terriermon] or [Lopmon] in its name from your trash without paying the cost.","-","-"],"card_number":"ST17-04","card_level":"U","image_link":"https://i.imgur.com/sTKzU35.png","LOCAL_NUMBER":16279},
{"name":"가르고몬","color":"녹흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Beastkin","dp":5000,"cost":6,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] Lv.3 w/[Terriermon]/[Lopmon] in name: Cost 2[Your Turn] [Once Per Turn] When this Digimon becomes suspended, 1 of your Digimon gains ＜Jamming＞ for the turn.","-","-"],"card_number":"ST17-05","card_level":"C","image_link":"https://i.imgur.com/8QLkyRl.png","LOCAL_NUMBER":16280},
{"name":"래피드몬(아머체)","color":"녹황","level":4,"type":"디지몬","attribute":"Armor Form 백신 Holy Warrior","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] Lv.3 w/[Terriermon] in name: Cost 3＜Blocker＞ ＜Armor Purge＞ [All Turns] [Once Per Turn] When this Digimon becomes suspended, 1 of your opponent's Digimon and all of their Security Digimon get -4000 DP until the end of their turn.","-","-"],"card_number":"ST17-06","card_level":"SR","image_link":"https://i.imgur.com/RXEuaXo.png","LOCAL_NUMBER":16281},
{"name":"래피드몬","color":"녹흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","dp":7000,"cost":7,"evolution_cost":["Lv.4~5","Lv.3~4"],"effect":["[Digivolve] Lv.4 w/[Gargomon]/[Rapidmon] in name: Cost 3[On Play] [When Digivolving] ＜De-Digivolve 1＞ 1 of your opponent's Digimon. Then, if you have a green Tamer, until the end of your opponent's turn, your opponent's effects can't delete this Digimon or return it to the hand or deck.","-","-"],"card_number":"ST17-07","card_level":"C","image_link":"https://i.imgur.com/Mq3uwDR.png","LOCAL_NUMBER":16282},
{"name":"세인트가르고몬 ACE","color":"녹흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Machine","dp":12000,"cost":7,"evolution_cost":["Lv.5~6","Lv.4~5"],"effect":["[Digivolve] [Rapidmon] in name: Cost 5[Hand] [Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) ＜Blocker＞ ＜Reboot＞ [When Digivolving] Suspend 2 of your opponent's Digimon or Tamers. Then, 2 of their Digimon or Tamers can't unsuspend or digivolve until the end of their turn. [When Digivolving] [End of Attack] [Once Per Turn] You may unsuspend this Digimon.","-","-"],"card_number":"ST17-08","card_level":"SR","image_link":"https://i.imgur.com/f5wJzuX.png","LOCAL_NUMBER":16283},
{"name":"케루비몬(악)","color":"녹자","level":6,"type":"디지몬","attribute":"궁극체 백신 Cherub","dp":12000,"cost":12,"evolution_cost":["Lv.5~6","Lv.4~5"],"effect":["[Digivolve] [Antylamon]: Cost 3＜Alliance＞ [When Digivolving] You may delete 1 level 4 or lower Digimon. Then, you may play 1 level 4 or lower green or purple Digimon card from your hand or trash without paying the cost.","-","-"],"card_number":"ST17-09","card_level":"R","image_link":"https://i.imgur.com/EtMAJef.png","LOCAL_NUMBER":16284},
{"name":"곽소룡","color":"녹","type":"테이머","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory. [Main] By placing this Tamer and 1 [Gargomon] and 1 [Rapidmon] from your trash in any order as one of your [Terriermon]'s bottom digivolution cards, that Digimon may digivolve into [MegaGargomon] in the hand for a digivolution cost of 4, ignoring its digivolution requirements. If this effect digivolved, that Digimon gains ＜Rush＞ for the turn.","-","-"],"card_number":"ST17-10","card_level":"R","image_link":"https://i.imgur.com/71SodIj.png","LOCAL_NUMBER":16285},
{"name":"더블 타이푼","color":"녹","type":"옵션","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["[Main] Reveal the top 3 cards of your deck. Add 1 green Digimon card and 1 such Tamer card among them to the hand. Return the rest to the bottom of the deck. Then, place this card in the battle area. [Main] ＜Delay＞ ・ You may play 1 [Terriermon] or [Lopmon] from your hand without paying the cost.","-","-"],"card_number":"ST17-11","card_level":"R","image_link":"https://i.imgur.com/eiA9Jbv.png","LOCAL_NUMBER":16286},
{"name":"자이언트 미사일","color":"녹","type":"옵션","attribute":"- -","dp":"-","cost":8,"evolution_cost":["-","-"],"effect":["[Main] Suspend 1 of your opponent's Digimon. Then, return 1 of their suspended Digimon to the bottom of the deck. 1 of their Digimon can't unsuspend until the end of their turn.","-","-"],"card_number":"ST17-12","card_level":"U","image_link":"https://i.imgur.com/rFTrEi2.png","LOCAL_NUMBER":16287},
{"name":"매그너몬","color":"흑청","level":4,"type":"디지몬","attribute":"Armor Form 프리 Holy Warrior/Royal Knight","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] [Veemon]: Cost 3[Security] ＜De-Digivolve 1＞ 1 Digimon. At the end of the battle, 1 of your Digimon may digivolve into this card without paying the digivolution cost. ＜Blocker＞ ＜Armor Purge＞ [When Digivolving] Trash the top digivolution card of 1 of your opponent's Digimon for each of that Digimon's colors. Then, return 1 of your opponent's Digimon with no digivolution cards to the hand.","-","-"],"card_number":"ST17-13","card_level":"SR","image_link":"https://i.imgur.com/ScnynmD.png","LOCAL_NUMBER":16288}]

ST18=[
{"name":"플러피몬","color":"녹","level":2,"type":"디지타마","attribute":"幼年期 - 小鳥型/リベレイター","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【アタック時】[ターンに1回]このデジモンのDP以下の他のデジモン1体をレストできる。"],"card_number":"ST18-01","card_level":"C","image_link":"https://i.imgur.com/sps7yMq.png","LOCAL_NUMBER":16289},
{"name":"피요몬","color":"녹적","level":3,"type":"디지몬","attribute":"成長期 ワクチン種 ヒナ鳥型","dp":3000,"cost":3,"evolution_cost":["Lv.2~1","Lv.2~1"],"effect":["≪不屈≫（進化元を持つこのデジモンが消滅したとき、このカードをコストを支払わずに登場させる）","-","-"],"card_number":"ST18-02","card_level":"C","image_link":"https://i.imgur.com/uCCBO1Y.png","LOCAL_NUMBER":16290},
{"name":"팔코몬","color":"녹","level":3,"type":"디지몬","attribute":"成長期 ワクチン種 鳥型","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【アタック時】相手のデジモン1体をレストさせる。","-","-"],"card_number":"ST18-03","card_level":"C","image_link":"https://i.imgur.com/yzLBguR.png","LOCAL_NUMBER":16291},
{"name":"프테로몬","color":"녹","level":3,"type":"디지몬","attribute":"成長期 データ種 鳥竜型/リベレイター","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【登場時】自分のデッキの上から3枚オープンする。その中の特徴に「鳥」を含むカード1枚と特徴に「ヴォルテクスウォリアー」/「リベレイター」を持つカード1枚を手札に加える。残りはデッキの下に戻す。","-","【自分のターン】このデジモンをDP+2000。"],"card_number":"ST18-04","card_level":"R","image_link":"https://i.imgur.com/2slIDwx.png","LOCAL_NUMBER":16292},
{"name":"레드펭귄몬","color":"녹","level":3,"type":"디지몬","attribute":"成長期 データ種 鳥型","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【お互いのターン】[ターンに1回]このデジモンが効果でレストしたとき、相手のターン終了まで、特徴に「鳥」を含むか特徴に「ヴォルテクスウォリアー」を持つ自分のデジモン1体をDP+3000。","-","≪貫通≫（このデジモンがアタックしたバトルで相手のデジモンを消滅させたとき、アタック終了前にチェックする）"],"card_number":"ST18-05","card_level":"U","image_link":"https://i.imgur.com/p2kIpDm.png","LOCAL_NUMBER":16293},
{"name":"키위몬","color":"녹","level":4,"type":"디지몬","attribute":"成熟期 データ種 古代鳥型","dp":3000,"cost":3,"evolution_cost":["Lv.3~2","-"],"effect":["【登場時】【消滅時】相手のデジモン1体をレストさせる。〈ルール〉特徴:タイプ「植物型」を持つ。","-","-"],"card_number":"ST18-06","card_level":"C","image_link":"https://i.imgur.com/62cOXo6.png","LOCAL_NUMBER":16294},
{"name":"꼬끼몬","color":"녹","level":4,"type":"디지몬","attribute":"成熟期 データ種 巨鳥型","dp":4000,"cost":4,"evolution_cost":["Lv.3~2","-"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）","-","≪貫通≫（このデジモンがアタックしたバトルで相手のデジモンを消滅させたとき、アタック終了前にチェックする）"],"card_number":"ST18-07","card_level":"U","image_link":"https://i.imgur.com/hcVGahN.png","LOCAL_NUMBER":16295},
{"name":"게일몬","color":"녹","level":4,"type":"디지몬","attribute":"成熟期 データ種 鳥竜型/リベレイター","dp":6000,"cost":6,"evolution_cost":["Lv.3~2","-"],"effect":["【セキュリティ】自分の手札/トラッシュから、特徴に「リベレイター」を持つ登場コスト4以下のカード1枚をコストを支払わずに登場できる。≪ヴォルテクス≫（自分のターン終了時、このデジモンで相手のデジモンにアタックできる。この効果では、登場したターンでもアタックできる）","-","【自分のターン】このデジモンをDP+2000。"],"card_number":"ST18-08","card_level":"SR","image_link":"https://i.imgur.com/06ANs8S.png","LOCAL_NUMBER":16296},
{"name":"뿌띠몬","color":"녹","level":5,"type":"디지몬","attribute":"完全体 データ種 鳥型","dp":7000,"cost":6,"evolution_cost":["Lv.4~3","-"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【消滅時】自分の手札から、特徴に「鳥」/「植物型」を含むDP3000以下のデジモンカード1枚をコストを支払わずに登場できる。〈ルール〉特徴:タイプ「植物型」を持つ。","-","-"],"card_number":"ST18-09","card_level":"C","image_link":"https://i.imgur.com/eewtg85.png","LOCAL_NUMBER":16297},
{"name":"그랑게일몬","color":"녹","level":5,"type":"디지몬","attribute":"完全体 データ種 鳥竜型/ヴォルテクスウォリアー/リベレイター","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【登場時】【進化時】デジモン1体をレストさせる。この効果で自分のデジモンがレストしたなら、自分の手札から、特徴に「鳥」を含むDP3000以下のデジモンカード1枚をコストを支払わずに登場できる。","-","【自分のターン】[ターンに1回]このデジモンが相手のデジモンにアタックしたとき、このデジモンをアクティブにできる。"],"card_number":"ST18-10","card_level":"R","image_link":"https://i.imgur.com/8zXRERp.png","LOCAL_NUMBER":16298},
{"name":"패롯몬","color":"녹","level":5,"type":"디지몬","attribute":"完全体 ワクチン種 巨鳥型","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【登場時】相手のデジモン1体をレストさせる。その後、相手のターン終了まで、相手のデジモン1体はアクティブにならない。","-","≪貫通≫（このデジモンがアタックしたバトルで相手のデジモンを消滅させたとき、アタック終了前にチェックする）"],"card_number":"ST18-11","card_level":"U","image_link":"https://i.imgur.com/sP9uL62.png","LOCAL_NUMBER":16299},
{"name":"제퍼가몬","color":"녹","level":6,"type":"디지몬","attribute":"究極体 データ種 魔法騎士型/ヴォルテクスウォリアー/リベレイター","dp":11000,"cost":11,"evolution_cost":["Lv.5~3","-"],"effect":["≪ヴォルテクス≫（自分のターン終了時、このデジモンで相手のデジモンにアタックできる。この効果では、登場したターンでもアタックできる）【進化時】デジモン1体をレストさせる。その後、デジモン1体をアクティブにする。【お互いのターン】[ターンに1回]デジモンがアクティブになったとき、ターン終了まで、このデジモンは相手のデジモンの効果を受けず、DP+3000。〈ルール〉特徴:タイプ「鳥竜型」を持つ。","-","-"],"card_number":"ST18-12","card_level":"SR","image_link":"https://i.imgur.com/Ouu5B4A.png","LOCAL_NUMBER":16300},
{"name":"크로스몬","color":"녹","level":6,"type":"디지몬","attribute":"究極体 ワクチン種 巨鳥型","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["≪不屈≫（進化元を持つこのデジモンが消滅したとき、このカードをコストを支払わずに登場させる）【登場時】【進化時】レスト状態の相手のデジモン1体を手札に戻す。","-","-"],"card_number":"ST18-13","card_level":"U","image_link":"https://i.imgur.com/V1m4T4L.png","LOCAL_NUMBER":16301},
{"name":"카자마 쇼토","color":"녹","level":"-","type":"테이머","attribute":"- - リベレイター","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["【自分のターン開始時】メモリーが2以下なら、3にする。【自分のターン】自分のデジモンが相手のデジモンにアタックしたとき、このテイマーをレストさせることで、アタックの対象を他の相手のデジモンかプレイヤーに変更する。","【セキュリティ】このカードをコストを支払わずに登場させる。","-"],"card_number":"ST18-14","card_level":"R","image_link":"https://i.imgur.com/OKQ05dK.png","LOCAL_NUMBER":16302},
{"name":"아네모이 엠브레이스","color":"녹","level":"-","type":"옵션","attribute":"- - リベレイター","dp":"-","cost":5,"evolution_cost":["-","-"],"effect":["【メイン】デジモン1体をレストさせる。この効果で自分のデジモンがレストしたなら、レスト状態の相手のデジモン1体をデッキの下に戻す。その後、デジモン1体をアクティブにする。","【セキュリティ】レスト状態の相手のデジモン1体をデッキの下に戻す。","-"],"card_number":"ST18-15","card_level":"U","image_link":"https://i.imgur.com/5ISD81e.png","LOCAL_NUMBER":16303}]



ST19=[
{"name":"캬로몬","color":"황","level":2,"type":"디지타마","attribute":"幼年期 - レッサー型/リベレイター","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【アタック時】[ターンに1回]他の自分のデジモンがいるなら、≪1ドロー≫（自分のデッキからカードを1枚引く）。"],"card_number":"ST19-01","card_level":"C","image_link":"https://i.imgur.com/GXKBHK5.png","LOCAL_NUMBER":16304},
{"name":"정크몬","color":"황","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["≪デコイ《特徴「パペット型」》≫（特徴に「パペット型」を持つ他の自分のデジモンが相手の効果で消滅するとき、このデジモンを消滅させることで、そのデジモン1体は消滅しない）","-","≪防壁≫（このデジモンがバトルで消滅するとき、自分のセキュリティを上から1枚破棄することで、消滅しない）"],"card_number":"ST19-02","card_level":"U","image_link":"https://i.imgur.com/NVsmrI0.png","LOCAL_NUMBER":16305},
{"name":"슈몬","color":"황","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型/リベレイター","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【登場時】自分のデッキの上から3枚オープンする。その中の特徴に「パペット型」を持つカード1枚と特徴に「リベレイター」を持つカード1枚を手札に加える。残りはデッキの下に戻す。","-","【自分のターン】相手のセキュリティデジモン全てをDP-3000。"],"card_number":"ST19-03","card_level":"R","image_link":"https://i.imgur.com/19Fn7FB.png","LOCAL_NUMBER":16306},
{"name":"폰체스몬(백)","color":"황흑","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型","dp":2000,"cost":3,"evolution_cost":["Lv.2~1","Lv.2~1"],"effect":["【登場時】自分の手札から、特徴に「パペット型」を持つカード1枚を破棄することで、≪2ドロー≫（自分のデッキからカードを2枚引く）。","-","≪再起動≫（このデジモンは相手のアクティブフェイズでもアクティブになる）"],"card_number":"ST19-04","card_level":"C","image_link":"https://i.imgur.com/VEDUM4J.png","LOCAL_NUMBER":16307},
{"name":"폰체스몬(흑)","color":"흑황","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型","dp":2000,"cost":3,"evolution_cost":["Lv.2~1","Lv.2~1"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【消滅時】自分の手札から、特徴に「パペット型」を持つカード1枚を破棄することで、≪2ドロー≫（自分のデッキからカードを2枚引く）。","-","-"],"card_number":"ST19-05","card_level":"C","image_link":"https://i.imgur.com/DxtYocv.png","LOCAL_NUMBER":16308},
{"name":"도그몬","color":"황","level":4,"type":"디지몬","attribute":"成熟期 データ種 パペット型","dp":4000,"cost":4,"evolution_cost":["Lv.3~2","-"],"effect":["【登場時】【消滅時】相手のターン終了まで、相手のデジモン1体に≪Sアタック-1≫（このデジモンがチェックする枚数-1）を与える。","-","-"],"card_number":"ST19-06","card_level":"C","image_link":"https://i.imgur.com/CDLHUvL.png","LOCAL_NUMBER":16309},
{"name":"토브캐트몬","color":"황","level":4,"type":"디지몬","attribute":"成熟期 データ種 パペット型/X抗体","dp":5000,"cost":5,"evolution_cost":["Lv.3~2","-"],"effect":["≪ジャミング≫（このデジモンはセキュリティデジモンとのバトルでは消滅しない）","-","≪防壁≫（このデジモンがバトルで消滅するとき、自分のセキュリティを上から1枚破棄することで、消滅しない）"],"card_number":"ST19-07","card_level":"U","image_link":"https://i.imgur.com/DGrVvlh.png","LOCAL_NUMBER":16310},
{"name":"슈슈몬","color":"황","level":4,"type":"디지몬","attribute":"成熟期 ウィルス種 パペット型/リベレイター","dp":5000,"cost":6,"evolution_cost":["Lv.3~2","-"],"effect":["【セキュリティ】自分の手札/トラッシュから、特徴に「リベレイター」を持つ登場コスト4以下のカード1枚をコストを支払わずに登場できる。≪オーバークロック《特徴「パペット型」》≫（自分のターン終了時、自分のトークンか特徴に「パペット型」を持つ他の自分のデジモン1体を消滅させることで、このデジモンでレストせずにプレイヤーにアタックする）","-","【自分のターン】相手のセキュリティデジモン全てをDP-3000。"],"card_number":"ST19-08","card_level":"SR","image_link":"https://i.imgur.com/FHGLMez.png","LOCAL_NUMBER":16311},
{"name":"팬더몬","color":"황","level":5,"type":"디지몬","attribute":"完全体 データ種 パペット型","dp":7000,"cost":6,"evolution_cost":["Lv.4~3","-"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【消滅時】自分の手札から、特徴に「パペット型」を持つLv.3のデジモンカード1枚をコストを支払わずに登場できる。","-","-"],"card_number":"ST19-09","card_level":"C","image_link":"https://i.imgur.com/Ii0oUqL.png","LOCAL_NUMBER":16312},
{"name":"엑스티라노몬","color":"황녹","level":5,"type":"디지몬","attribute":"完全体 ワクチン種 パペット型","dp":7000,"cost":7,"evolution_cost":["Lv.4~4","Lv.4~4"],"effect":["名称に「ティラノモン」/「レアモン」を含むLv.4:コスト3≪アーマー解除≫（このデジモンが消滅するとき、このデジモンに重ねられているカードを上から1枚破棄することで、消滅しない）名称に「ティラノモン」/「レアモン」を含むLv.4×特徴に「パペット型」を持つLv.4","-","≪防壁≫（このデジモンがバトルで消滅するとき、自分のセキュリティを上から1枚破棄することで、消滅しない）"],"card_number":"ST19-10","card_level":"U","image_link":"https://i.imgur.com/HKk4lDY.png","LOCAL_NUMBER":16313},
{"name":"샤프로몬","color":"황","level":5,"type":"디지몬","attribute":"完全体 ウィルス種 パペット型/リベレイター","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【登場時】【進化時】ターン終了まで、相手のデジモン1体をDP-3000。デジモンが3体以上いるなら、このDPマイナス効果の数値-3000。","-","【お互いのターン】[ターンに1回]このデジモンが自分の効果以外でバトルエリアを離れるとき、自分のトークンか特徴に「パペット型」を持つ他の自分のデジモン1体を消滅させることで、離れない。"],"card_number":"ST19-11","card_level":"R","image_link":"https://i.imgur.com/n9rLfGy.png","LOCAL_NUMBER":16314},
{"name":"상드리몬","color":"황","level":6,"type":"디지몬","attribute":"究極体 ウィルス種 パペット型/リベレイター","dp":11000,"cost":11,"evolution_cost":["Lv.5~3","-"],"effect":["≪オーバークロック《特徴「パペット型」》≫（自分のターン終了時、自分のトークンか特徴に「パペット型」を持つ他の自分のデジモン1体を消滅させることで、このデジモンでレストせずにプレイヤーにアタックする）≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【進化時】「使い魔」（デジモン・黄・DP3000・【消滅時】ターン終了まで、相手のデジモン1体をDP-3000。）トークン2体を登場できる。","-","-"],"card_number":"ST19-12","card_level":"SR","image_link":"https://i.imgur.com/1PT2tFb.png","LOCAL_NUMBER":16315},
{"name":"신퍼펫몬","color":"황","level":6,"type":"디지몬","attribute":"究極体 ワクチン種 パペット型","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["名称に「もんざえモン」/「ヌメモン」を含むLv.5:コスト3≪アーマー解除≫（このデジモンが消滅するとき、このデジモンに重ねられているカードを上から1枚破棄することで、消滅しない）【登場時】【進化時】自分のトラッシュから、名称に「ヌメモン」を含むか特徴に「パペット型」を持つLv.5以下のカード1枚をこのデジモンの進化元の下に置くことで、≪リカバリー+1《デッキ》≫（自分のデッキの上から1枚をセキュリティの上に置く）。","-","-"],"card_number":"ST19-13","card_level":"U","image_link":"https://i.imgur.com/I0vH7if.png","LOCAL_NUMBER":16316},
{"name":"키노사키 아리사","color":"황","level":"-","type":"테이머","attribute":"- - リベレイター","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["【自分のターン開始時】メモリーが2以下なら、3にする。【自分のターン】自分のトークンか特徴に「パペット型」を持つ自分のデジモンが効果で登場したとき、このテイマーをレストさせることで、ターン終了まで、そのデジモン1体は≪速攻≫（このデジモンは登場したターンでもアタックできる）を得る。","【セキュリティ】このカードをコストを支払わずに登場させる。","-"],"card_number":"ST19-14","card_level":"R","image_link":"https://i.imgur.com/fY8AHdN.png","LOCAL_NUMBER":16317},
{"name":"노블 패밀리아츠","color":"황","level":"-","type":"옵션","attribute":"- - リベレイター","dp":"-","cost":5,"evolution_cost":["-","-"],"effect":["【メイン】ターン終了まで、相手のデジモン1体をDP-6000。デジモンが3体以上いるなら、このDPマイナス効果の数値-6000。","【セキュリティ】このカードの【メイン】効果を発揮する。","-"],"card_number":"ST19-15","card_level":"U","image_link":"https://i.imgur.com/aqXoqem.png","LOCAL_NUMBER":16318}
]

// 16325 까지사용함