
ST12=
[{"name":"구리몬","color":"적","level":2,"type":"디지타마","attribute":"유년기 - Lesser","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST12-01","card_level":"U","image_link":"https://i.imgur.com/3S7X19i.png","LOCAL_NUMBER":16200},
{"name":"캔들몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 데이터 Flame","cost":2,"evolution_cost":["0 from Lv.2","-"],"effect":["-","-","-"],"card_number":"ST12-02","card_level":"C","image_link":"https://i.imgur.com/vGIUVbt.png","LOCAL_NUMBER":16201},
{"name":"황금톱니몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 백신 Machine","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[All Turns] Players can't reduce play costs.","-","-"],"card_number":"ST12-03","card_level":"C","image_link":"https://i.imgur.com/Kfl449r.png","LOCAL_NUMBER":16202},
{"name":"헉몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 데이터 Mini Dragon","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[Your Turn][Once Per Turn] When you play a Digimon with [Sistermon] in its name, gain 1 memory.","-","-"],"card_number":"ST12-04","card_level":"R","image_link":"https://i.imgur.com/paJfwwK.png","LOCAL_NUMBER":16203},
{"name":"메라몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 데이터 Flame","cost":4,"evolution_cost":["1 from Lv.3","-"],"effect":["-","-","-"],"card_number":"ST12-05","card_level":"U","image_link":"https://i.imgur.com/S6wQrAR.png","LOCAL_NUMBER":16204},
{"name":"바오헉몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 데이터 Dinosaur","cost":5,"evolution_cost":["2 from Lv.3","-"],"effect":["-","-","-"],"card_number":"ST12-06","card_level":"C","image_link":"https://i.imgur.com/xmrUruS.png","LOCAL_NUMBER":16205},
{"name":"데드메라몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 데이터 Flame","cost":6,"evolution_cost":["3 from Lv.4","-"],"effect":["-","-","-"],"card_number":"ST12-07","card_level":"C","image_link":"https://i.imgur.com/hx9F47f.png","LOCAL_NUMBER":16206},
{"name":"세이버헉몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 데이터 Dragonkin","cost":7,"evolution_cost":["3 from Lv.4","-"],"effect":["[When Digivolving] This Digimon may also attack your opponent's unsuspended Digimon for the turn.","-","-"],"card_number":"ST12-08","card_level":"R","image_link":"https://i.imgur.com/ms7GJjU.png","LOCAL_NUMBER":16207},
{"name":"볼케몬","color":"적흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Cyborg","cost":8,"evolution_cost":["4 from Lv.4","Black"],"effect":["＜Blocker＞ (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)","-","-"],"card_number":"ST12-09","card_level":"U","image_link":"https://i.imgur.com/jdISxum.png","LOCAL_NUMBER":16208},
{"name":"제스몬","color":"적","level":6,"type":"디지몬","attribute":"궁극체 데이터 Holy Warrior/Royal Knight","cost":12,"evolution_cost":["4 from Lv.5","-"],"effect":["[When Digivolving] ＜Blitz＞ (This Digimon can attack when your opponent has 1 or more memory.)[When Attacking] You may play 1 Digimon card with [Sistermon] in its name from your hand without paying its memory cost.[Your Turn][Once Per Turn] When you play another Digimon by an effect, this Digimon gets +3000 DP and gains ＜Security Attack +1＞ for the turn. (This Digimon checks 1 additional security card.)","-","-"],"card_number":"ST12-10","card_level":"SR","image_link":"https://i.imgur.com/N6aTxd6.png","LOCAL_NUMBER":16209},
{"name":"간쿠몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 데이터 Holy Warrior/Royal Knight","cost":12,"evolution_cost":["3 from Lv.5","Red"],"effect":["[When Digivolving] You may play 1 [Huckmon] or 1 Digimon card with [Sistermon] in its name in your trash without paying its memory cost.[Your Turn][Once Per Turn] When you play another Digimon by an effect, ＜De-Digivolve 1＞ up to 2 of your opponent's Digimon. (Trash 1 card from the top of one of your opponent's Digimon. If it has no digivolution cards, or becomes a level 3 Digimon, you can't trash any more cards.)","-","-"],"card_number":"ST12-11","card_level":"SR","image_link":"https://i.imgur.com/KUSqdl1.png","LOCAL_NUMBER":16210},
{"name":"시스터몬 블랑","color":"백","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","cost":3,"evolution_cost":["-","-"],"effect":["[On Play] By trashing 1 card in your hand, ＜Draw 2＞. (Draw 2 cards from your deck.)[All Turns] While you have a Digimon in play with [Huckmon] in its name or [Royal Knight] in its traits, this Digimon gains ＜Decoy (Red/Black)＞.(When one of your other red or black Digimon would be deleted by an opponent's effect, you may delete this Digimon to prevent that deletion.)","-","-"],"card_number":"ST12-12","card_level":"U","image_link":"https://i.imgur.com/2Fiq8uV.png","LOCAL_NUMBER":16211},
{"name":"시스터몬 느와르","color":"백","level":4,"type":"디지몬","attribute":"성숙기 데이터 Puppet","cost":4,"evolution_cost":["-","-"],"effect":["[On Play] Reveal the top 3 cards of your deck. Add 1 card with [Huckmon] in its name or [Royal Knight] in its traits among them to your hand. Trash the rest.[All Turns] All of your Digimon with [Huckmon] in their names and [Royal Knight] in their traits gain ＜Reboot＞. (Unsuspend this Digimon during your opponent's unsuspend phase.)*Also treat as if name is [Sistermon Noir] and traits include [Virus].","-","-"],"card_number":"ST12-13","card_level":"U","image_link":"https://i.imgur.com/1oLl0Yr.png","LOCAL_NUMBER":16212},
{"name":"아우스 제네릭스","color":"적","type":"옵션","attribute":"- -","cost":1,"evolution_cost":["-","-"],"effect":["[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if you have a Digimon with [Huckmon] in its name or [Royal Knight] in its traits in play, gain 1 memory, and 1 of your Digimon gains ＜Piercing＞ for the turn. (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would.)","-","-"],"card_number":"ST12-14","card_level":"C","image_link":"https://i.imgur.com/g24Nhic.png","LOCAL_NUMBER":16213},
{"name":"사제의 여로","color":"적","type":"옵션","attribute":"- Royal Knight","cost":2,"evolution_cost":["-","-"],"effect":["[Main] Reveal the top 3 cards of your deck. Add 1 card with [Huckmon] or [Sistermon] in its name or [Royal Knight] in its traits among them to your hand. Trash the rest. Then, place this card in your Battle Area.[Main] ＜Delay＞ (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.)・The next time one of your Digimon would digivolve this turn, reduce the digivolution cost by 1.","-","-"],"card_number":"ST12-15","card_level":"C","image_link":"https://i.imgur.com/sg6IY2i.png","LOCAL_NUMBER":16214},
{"name":"지신! 신명! 신치! 친부!","color":"흑","type":"옵션","attribute":"- -","cost":7,"evolution_cost":["-","-"],"effect":["While you have a Digimon with [Huckmon] or [Sistermon] in its name or [Royal Knight] in its traits in play, you may use this card without meeting its color requirements.[Main] Delete 1 of your opponent's Digimon with a play cost of 13 or less.","-","-"],"card_number":"ST12-16","card_level":"R","image_link":"https://i.imgur.com/VGXSGOt.png","LOCAL_NUMBER":16215}

]