
ST12=
[{"name":"구리몬","color":"적","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST12-01","card_level":"U","image_link":"https://i.imgur.com/3S7X19i.png","LOCAL_NUMBER":16200},
{"name":"캔들몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 데이터 Flame","dp":3000,"cost":2,"evolution_cost":["Lv.1~2","-"],"effect":["-","-","-"],"card_number":"ST12-02","card_level":"C","image_link":"https://i.imgur.com/vGIUVbt.png","LOCAL_NUMBER":16201},
{"name":"황금톱니몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 백신 Machine","dp":3000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[All Turns] Players can't reduce play costs.","-","-"],"card_number":"ST12-03","card_level":"C","image_link":"https://i.imgur.com/Kfl449r.png","LOCAL_NUMBER":16202},
{"name":"헉몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 데이터 Mini Dragon","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[Your Turn][Once Per Turn] When you play a Digimon with [Sistermon] in its name, gain 1 memory.","-","-"],"card_number":"ST12-04","card_level":"R","image_link":"https://i.imgur.com/paJfwwK.png","LOCAL_NUMBER":16203},
{"name":"메라몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 데이터 Flame","dp":4000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["-","-","-"],"card_number":"ST12-05","card_level":"U","image_link":"https://i.imgur.com/S6wQrAR.png","LOCAL_NUMBER":16204},
{"name":"바오헉몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 데이터 Dinosaur","dp":6000,"cost":5,"evolution_cost":["Lv.2~3","-"],"effect":["-","-","-"],"card_number":"ST12-06","card_level":"C","image_link":"https://i.imgur.com/xmrUruS.png","LOCAL_NUMBER":16205},
{"name":"데드메라몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 데이터 Flame","dp":9000,"cost":6,"evolution_cost":["Lv.3~4","-"],"effect":["-","-","-"],"card_number":"ST12-07","card_level":"C","image_link":"https://i.imgur.com/hx9F47f.png","LOCAL_NUMBER":16206},
{"name":"세이버헉몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 데이터 Dragonkin","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","-"],"effect":["[When Digivolving] This Digimon may also attack your opponent's unsuspended Digimon for the turn.","-","-"],"card_number":"ST12-08","card_level":"R","image_link":"https://i.imgur.com/ms7GJjU.png","LOCAL_NUMBER":16207},
{"name":"볼케몬","color":"적흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Cyborg","dp":9000,"cost":8,"evolution_cost":["Lv.3~4","Black"],"effect":["＜Blocker＞ (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)","-","-"],"card_number":"ST12-09","card_level":"U","image_link":"https://i.imgur.com/jdISxum.png","LOCAL_NUMBER":16208},
{"name":"제스몬","color":"적","level":6,"type":"디지몬","attribute":"궁극체 데이터 Holy Warrior/Royal Knight","dp":12000,"cost":12,"evolution_cost":["Lv.4~5","-"],"effect":["[When Digivolving] ＜Blitz＞ (This Digimon can attack when your opponent has 1 or more memory.)[When Attacking] You may play 1 Digimon card with [Sistermon] in its name from your hand without paying its memory cost.[Your Turn][Once Per Turn] When you play another Digimon by an effect, this Digimon gets +3000 DP and gains ＜Security Attack +1＞ for the turn. (This Digimon checks 1 additional security card.)","-","-"],"card_number":"ST12-10","card_level":"SR","image_link":"https://i.imgur.com/N6aTxd6.png","LOCAL_NUMBER":16209},
{"name":"간쿠몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 데이터 Holy Warrior/Royal Knight","dp":11000,"cost":12,"evolution_cost":["Lv.4~5","Red"],"effect":["[When Digivolving] You may play 1 [Huckmon] or 1 Digimon card with [Sistermon] in its name in your trash without paying its memory cost.[Your Turn][Once Per Turn] When you play another Digimon by an effect, ＜De-Digivolve 1＞ up to 2 of your opponent's Digimon. (Trash 1 card from the top of one of your opponent's Digimon. If it has no digivolution cards, or becomes a level 3 Digimon, you can't trash any more cards.)","-","-"],"card_number":"ST12-11","card_level":"SR","image_link":"https://i.imgur.com/KUSqdl1.png","LOCAL_NUMBER":16210},
{"name":"시스터몬 블랑","color":"백","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","dp":3000,"cost":3,"evolution_cost":["-","-"],"effect":["[On Play] By trashing 1 card in your hand, ＜Draw 2＞. (Draw 2 cards from your deck.)[All Turns] While you have a Digimon in play with [Huckmon] in its name or [Royal Knight] in its traits, this Digimon gains ＜Decoy (Red/Black)＞.(When one of your other red or black Digimon would be deleted by an opponent's effect, you may delete this Digimon to prevent that deletion.)","-","-"],"card_number":"ST12-12","card_level":"U","image_link":"https://i.imgur.com/2Fiq8uV.png","LOCAL_NUMBER":16211},
{"name":"시스터몬 느와르","color":"백","level":4,"type":"디지몬","attribute":"성숙기 데이터 Puppet","dp":5000,"cost":4,"evolution_cost":["-","-"],"effect":["[On Play] Reveal the top 3 cards of your deck. Add 1 card with [Huckmon] in its name or [Royal Knight] in its traits among them to your hand. Trash the rest.[All Turns] All of your Digimon with [Huckmon] in their names and [Royal Knight] in their traits gain ＜Reboot＞. (Unsuspend this Digimon during your opponent's unsuspend phase.)*Also treat as if name is [Sistermon Noir] and traits include [Virus].","-","-"],"card_number":"ST12-13","card_level":"U","image_link":"https://i.imgur.com/1oLl0Yr.png","LOCAL_NUMBER":16212},
{"name":"아우스 제네릭스","color":"적","type":"옵션","attribute":"- -","dp":"-","cost":1,"evolution_cost":["-","-"],"effect":["[Main] 1 of your Digimon gets +2000 DP for the turn. Then, if you have a Digimon with [Huckmon] in its name or [Royal Knight] in its traits in play, gain 1 memory, and 1 of your Digimon gains ＜Piercing＞ for the turn. (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would.)","-","-"],"card_number":"ST12-14","card_level":"C","image_link":"https://i.imgur.com/g24Nhic.png","LOCAL_NUMBER":16213},
{"name":"사제의 여로","color":"적","type":"옵션","attribute":"- Royal Knight","dp":"-","cost":2,"evolution_cost":["-","-"],"effect":["[Main] Reveal the top 3 cards of your deck. Add 1 card with [Huckmon] or [Sistermon] in its name or [Royal Knight] in its traits among them to your hand. Trash the rest. Then, place this card in your Battle Area.[Main] ＜Delay＞ (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.)・The next time one of your Digimon would digivolve this turn, reduce the digivolution cost by 1.","-","-"],"card_number":"ST12-15","card_level":"C","image_link":"https://i.imgur.com/sg6IY2i.png","LOCAL_NUMBER":16214},
{"name":"지신! 신명! 신치! 친부!","color":"흑","type":"옵션","attribute":"- -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["While you have a Digimon with [Huckmon] or [Sistermon] in its name or [Royal Knight] in its traits in play, you may use this card without meeting its color requirements.[Main] Delete 1 of your opponent's Digimon with a play cost of 13 or less.","-","-"],"card_number":"ST12-16","card_level":"R","image_link":"https://i.imgur.com/VGXSGOt.png","LOCAL_NUMBER":16215}]

ST13=
[{"name":"사쿳토몬","color":"흑","level":2,"type":"디지타마","attribute":"유년기 - Weapon","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST13-01","card_level":"U","image_link":"https://i.imgur.com/yTQKOS3.png","LOCAL_NUMBER":16216},
{"name":"즈바몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 백신 Weapon/Legend-Arms","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","Black"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's black or has [Legend-Arms] in its traits as its bottom digivolution card, you may reveal the top card of your deck. If that card is a Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less, you may play it without paying its memory cost. Add the rest to your hand.","-","-"],"card_number":"ST13-02","card_level":"U","image_link":"https://i.imgur.com/cWn3RTs.png","LOCAL_NUMBER":16217},
{"name":"즈바이거몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 백신 Weapon/Legend-Arms","dp":4000,"cost":5,"evolution_cost":["Lv.2~3","Black"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's black or has [Legend-Arms] in its traits as its bottom digivolution card, delete 1 of your opponent's Digimon with 5000 DP or less.","-","-"],"card_number":"ST13-03","card_level":"C","image_link":"https://i.imgur.com/fOocrOy.png","LOCAL_NUMBER":16218},
{"name":"듀라몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 백신 Weapon/Legend-Arms","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","Black"],"effect":["[Your Turn] When this Digimon would digivolve into a card in your hand that's black or has [Legend-Arms] in its traits, reduce the digivolution cost by 1.","-","-"],"card_number":"ST13-04","card_level":"U","image_link":"https://i.imgur.com/s0svzhS.png","LOCAL_NUMBER":16219},
{"name":"듀란다몬","color":"적","level":6,"type":"디지몬","attribute":"궁극체 백신 Holy Sword/Legend-Arms","dp":11000,"cost":11,"evolution_cost":["Lv.4~5","Black"],"effect":["[Your Turn][Once Per Turn] When one of your effects places a digivolution card under this Digimon, this Digimon gets +3000 DP and ＜Security Attack +1＞ for the turn. (This Digimon checks 1 additional security card.)[When Attacking] Reveal the top 3 cards of your deck. You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less among them without paying its memory cost. Place the rest at the bottom of your deck in any order.","-","-"],"card_number":"ST13-05","card_level":"SR","image_link":"https://i.imgur.com/i871B2m.png","LOCAL_NUMBER":16220},
{"name":"라그나로드몬","color":"적흑","level":7,"type":"디지몬","attribute":"궁극체 바이러스 Unique/Legend-Arms","dp":15000,"cost":15,"evolution_cost":["Lv.5~6","Black"],"effect":["DNA Digivolution: 0 from red Lv.6 + black Lv.6[When Digivolving] ＜Blitz＞ (This Digimon can attack when your opponent has 1 or more memory.) When DNA digivolving, for every 4 cards in this Digimon's digivolution cards, delete 1 of your opponent's Digimon with a play cost of 20 or less and trash the top card of your opponent's security stack.[All Turns][Once Per Turn] When a card is removed from a player's security stack, unsuspend this Digimon.","-","-"],"card_number":"ST13-06","card_level":"SR","image_link":"https://i.imgur.com/6HivZmd.png","LOCAL_NUMBER":16221},
{"name":"코테몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 데이터 Reptile","dp":3000,"cost":2,"evolution_cost":["Lv.1~2","-"],"effect":["-","-","-"],"card_number":"ST13-07","card_level":"C","image_link":"https://i.imgur.com/YbXcXeY.png","LOCAL_NUMBER":16222},
{"name":"치쿠리몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 바이러스 Mine","dp":3000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[All Turns] Players can't reduce play costs.","-","-"],"card_number":"ST13-08","card_level":"C","image_link":"https://i.imgur.com/JMyKk1m.png","LOCAL_NUMBER":16223},
{"name":"루도몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 데이터 Armor/Legend-Arms","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","Red"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's red or has [Legend-Arms] in its traits as its bottom digivolution card, you may reveal the top card of your deck. You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less among them without paying its memory cost. Add the rest to your hand.","-","-"],"card_number":"ST13-09","card_level":"U","image_link":"https://i.imgur.com/Sd2gpdj.png","LOCAL_NUMBER":16224},
{"name":"그라디몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Warrior","dp":4000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["-","-","-"],"card_number":"ST13-10","card_level":"C","image_link":"https://i.imgur.com/tilT8MA.png","LOCAL_NUMBER":16225},
{"name":"티아루도몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 데이터 Armor/Legend-Arms","dp":4000,"cost":5,"evolution_cost":["Lv.2~3","Red"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's red or has [Legend-Arms] in its traits as its bottom digivolution card, 1 of your Digimon gains ＜Reboot＞ until the end of your opponent's turn. (Unsuspend this Digimon during your opponent's unsuspend phase.)","-","-"],"card_number":"ST13-11","card_level":"U","image_link":"https://i.imgur.com/TyHmGaK.png","LOCAL_NUMBER":16226},
{"name":"나이트몬","color":"흑적","level":5,"type":"디지몬","attribute":"완전체 데이터 Warrior","dp":7000,"cost":5,"evolution_cost":["Lv.3~4","Red"],"effect":["-","-","-"],"card_number":"ST13-12","card_level":"C","image_link":"https://i.imgur.com/ZS7STAZ.png","LOCAL_NUMBER":16227},
{"name":"라이지루도몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Armor/Legend-Arms","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","Red"],"effect":["[Opponent's Turn] This Digimon can't be deleted by your opponent's effects.","-","-"],"card_number":"ST13-13","card_level":"R","image_link":"https://i.imgur.com/kWCbL3O.png","LOCAL_NUMBER":16228},
{"name":"브리웨루드라몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 데이터 Armor/Legend-Arms","dp":12000,"cost":11,"evolution_cost":["Lv.4~5","Red"],"effect":["[Your Turn][Once Per Turn] When one of your effects places a digivolution card under this Digimon, your opponent's effects can't delete this Digimon or return it to its owner's hand or deck until the end of their turn.[When Digivolving] Reveal the top 3 cards of your deck. You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less among them without paying its memory cost. Place the rest at the bottom of your deck in any order.","-","-"],"card_number":"ST13-14","card_level":"R","image_link":"https://i.imgur.com/0MxhpyD.png","LOCAL_NUMBER":16229},
{"name":"다이렉트 스매셔","color":"적","type":"옵션","attribute":"- -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["While you have a Digimon with [Legend-Arms] in its traits in play, you may use this card without meeting its color requirements.[Main] Delete 1 of your opponent's Digimon with the highest DP.","-","-"],"card_number":"ST13-15","card_level":"R","image_link":"https://i.imgur.com/SLOyILr.png","LOCAL_NUMBER":16230},
{"name":"모순공투","color":"흑적","type":"옵션","attribute":"- Legend-Arms","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Main] You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less in your hand without paying its memory cost. Then, place this card in your Battle Area.[Main] ＜Delay＞ (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.)・Reveal the top 4 cards of your deck. Place those cards on the top or bottom of your deck in any order.","-","-"],"card_number":"ST13-16","card_level":"C","image_link":"https://i.imgur.com/zF7pBl1.png","LOCAL_NUMBER":16231}]

ST14=[
{"name":"야몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST14-01","card_level":"U","image_link":"https://i.imgur.com/as9gqk9.png","LOCAL_NUMBER":16232},
{"name":"임프몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Evil","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[When Attacking] If you have 20 or more cards in your trash, this Digimon may digivolve into [Beelzemon] from your trash for a digivolution cost of 3, ignoring its digivolution requirements.","-","-"],"card_number":"ST14-02","card_level":"SR","image_link":"https://i.imgur.com/gMjEWeK.png","LOCAL_NUMBER":16233},
{"name":"캔들몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Flame","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[On Play] Trash the top 2 cards of your deck.[On Deletion] If you have 10 or more cards in your trash, ＜Draw 1＞. (Draw 1 card from your deck.)","-","-"],"card_number":"ST14-03","card_level":"U","image_link":"https://i.imgur.com/7QtY3Bv.png","LOCAL_NUMBER":16234},
{"name":"파스코몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Dark Animal","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["＜Blocker＞ (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[Your Turn] This Digimon can't attack players.","-","-"],"card_number":"ST14-04","card_level":"C","image_link":"https://i.imgur.com/RFX0yM8.png","LOCAL_NUMBER":16235},
{"name":"포큐파몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Puppet","dp":4000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["＜Blocker＞ (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.) [On Play] Trash the top 2 cards of your deck.","-","-"],"card_number":"ST14-05","card_level":"C","image_link":"https://i.imgur.com/HKe3i7p.png","LOCAL_NUMBER":16236},
{"name":"위치몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터 Wizard","dp":5000,"cost":5,"evolution_cost":["Lv.2~3","-"],"effect":["[When Digivolving] Trash the top 3 cards of your deck.","-","-"],"card_number":"ST14-06","card_level":"U","image_link":"https://i.imgur.com/gICncKF.png","LOCAL_NUMBER":16237},
{"name":"바알몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 프리 Wizard","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","-"],"effect":["[When Digivolving] Trash the top 3 cards of your deck.[When Digivolving] This Digimon gains \"[On Deletion] If there are 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying the cost\" until the end of your opponent's turn.","-","-"],"card_number":"ST14-07","card_level":"R","image_link":"https://i.imgur.com/wuQHQRp.png","LOCAL_NUMBER":16238},
{"name":"베르제브몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스 Demon Lord/Seven Great Demon Lords","dp":12000,"cost":12,"evolution_cost":["Lv.4~5","-"],"effect":["[When Digivolving] Trash the top 4 cards of your deck. [All Turns][Once Per Turn] When a card is trashed from your deck, gain 1 memory for every 10 cards in your trash.[Your Turn][Once Per Turn] When a card is trashed from your deck, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card) for the turn.","-","-"],"card_number":"ST14-08","card_level":"SR","image_link":"https://i.imgur.com/qEof3bp.png","LOCAL_NUMBER":16239},
{"name":"베르스타몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스 Wizard/Three Musketeers","dp":11000,"cost":13,"evolution_cost":["Lv.4~5","-"],"effect":["When you would play this card from your hand, reduce the play cost by 4 for every 10 cards in your trash.[All Turns][Once Per Turn] When a card is trashed from your deck, you may play 1 [Impmon] from your trash without paying the cost. The Digimon played by this effect gains ＜Rush＞ for the turn.[Opponent's Turn] When an opponent's Digimon attacks, trash the top card of your deck.","-","-"],"card_number":"ST14-09","card_level":"SR","image_link":"https://i.imgur.com/xksYDWz.png","LOCAL_NUMBER":16240},
{"name":"베르제브몬:블래스트 모드","color":"자","level":7,"type":"디지몬","attribute":"궁극체 바이러스 Demon Lord","dp":14000,"cost":14,"evolution_cost":["Lv.5~6","-"],"effect":["When this card is trashed from your deck, delete 1 of your opponent's level 3 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect. [When Digivolving] Unsuspend this Digimon. If you have 20 or more cards in your trash, gain 3 memory.","-","-"],"card_number":"ST14-10","card_level":"SR","image_link":"https://i.imgur.com/ocVRExR.png","LOCAL_NUMBER":16241},
{"name":"다영 & 진","color":"자","type":"테이머","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with [Evil], [Wizard], or [Demon Lord] in its traits among them to your hand. Place the rest at the bottom of your deck in any order. [Your Turn] When one of your Digimon digivolves into a purple Digimon, you may suspend this Tamer and return 1 card from your hand to your deck to gain 1 memory.","-","-"],"card_number":"ST14-11","card_level":"R","image_link":"https://i.imgur.com/yRhS0ef.png","LOCAL_NUMBER":16242},
{"name":"견원의흉탄","color":"자","type":"옵션","attribute":"- -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["When this card is trashed from your deck, you may place it in the battle area.  [Main] Delete 1 of your opponent's Digimon with the highest level. [Main]  ＜Delay＞ (After this card is placed, by trashing it the next turn or later, activate the effect below.) ・Return 1 purple Digimon card or Tamer card from your trash to your hand.","-","-"],"card_number":"ST14-12","card_level":"R","image_link":"https://i.imgur.com/b94gOAp.png","LOCAL_NUMBER":16243}]

ST15=[
{"name":"코로몬","color":"흑","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST15-01","card_level":"U","image_link":"https://i.imgur.com/swxQ1g6.png","LOCAL_NUMBER":16244},
{"name":"아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Reptile","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[Digivolve][Koromon]: Cost 0[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.","-","-"],"card_number":"ST15-02","card_level":"R","image_link":"https://i.imgur.com/dKh8VPd.png","LOCAL_NUMBER":16245},
{"name":"투명아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["-","-","-"],"card_number":"ST15-03","card_level":"U","image_link":"https://i.imgur.com/Q1WJCmk.png","LOCAL_NUMBER":16246},
{"name":"솔라몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Machine","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[On Play] Reveal the top card of your deck. If it's a black card, add it to your hand. Trash the rest.","-","-"],"card_number":"ST15-04","card_level":"C","image_link":"https://i.imgur.com/qMzljxS.png","LOCAL_NUMBER":16247},
{"name":"토이아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","dp":4000,"cost":4,"evolution_cost":["Lv.1~2","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.) [Your Turn] When this Digimon attacks a player, lose 2 memory.","-","-"],"card_number":"ST15-05","card_level":"C","image_link":"https://i.imgur.com/Cfx2Aye.png","LOCAL_NUMBER":16248},
{"name":"메카노몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Machine","dp":5000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["-","-","-"],"card_number":"ST15-06","card_level":"C","image_link":"https://i.imgur.com/XPxgXXs.png","LOCAL_NUMBER":16249},
{"name":"탱크몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 데이터 Cyborg","dp":6000,"cost":5,"evolution_cost":["Lv.2~3","-"],"effect":["＜Jamming＞ (This Digimon can't be deleted in battles against Security Digimon.)","-","-"],"card_number":"ST15-07","card_level":"C","image_link":"https://i.imgur.com/9laXQIr.png","LOCAL_NUMBER":16250},
{"name":"그레이몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Dinosaur","dp":5000,"cost":6,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] Lv.3 w/[Agumon] in name: Cost 2[Security] You may play 1 [Agumon] or 1 Tamer card with [Tai Kamiya] in its name from your hand or trash without paying the cost. ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST15-08","card_level":"SR","image_link":"https://i.imgur.com/LvD0TXc.png","LOCAL_NUMBER":16251},
{"name":"나이트몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Warrior","dp":7000,"cost":6,"evolution_cost":["Lv.3~4","-"],"effect":["[On Play] Delete 1 of your opponent's Digimon with a play cost of 5 or less.","-","-"],"card_number":"ST15-09","card_level":"C","image_link":"https://i.imgur.com/KBl5Xul.png","LOCAL_NUMBER":16252},
{"name":"안드로몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","-"],"effect":["[When Digivolving] ＜De-Digivolve 1＞ 1 of your opponent's Digimon. (Trash the top card. You can't trash past level 3 cards.)","-","-"],"card_number":"ST15-10","card_level":"U","image_link":"https://i.imgur.com/trJhLV9.png","LOCAL_NUMBER":16253},
{"name":"메탈그레이몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","dp":8000,"cost":8,"evolution_cost":["Lv.3~4","-"],"effect":["[Digivolve] Lv.4 w/[Greymon] in name: Cost 3＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST15-11","card_level":"R","image_link":"https://i.imgur.com/1ZYs7bC.png","LOCAL_NUMBER":16254},
{"name":"워그레이몬 ACE","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Dragonkin","dp":11000,"cost":6,"evolution_cost":["Lv.4~5","-"],"effect":["[Digivolve] Lv.5 w/[Greymon] in name: Cost 3[Hand][Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) ＜Blocker＞ [All Turns][Once Per Turn] When a card is removed from a security stack, you may unsuspend this Digimon.","-","-"],"card_number":"ST15-12","card_level":"SR","image_link":"https://i.imgur.com/pu1vGv2.png","LOCAL_NUMBER":16255},
{"name":"하이안드로몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Cyborg","dp":12000,"cost":11,"evolution_cost":["Lv.4~5","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target. [When Digivolving] Delete 1 of your opponent's Digimon with a play cost of 8 or less.","-","-"],"card_number":"ST15-13","card_level":"U","image_link":"https://i.imgur.com/Za3uH9G.png","LOCAL_NUMBER":16256},
{"name":"신태일","color":"흑","type":"테이머","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Start of Your Turn] If you have 2 or fewer memory, set it to 3. [All Turns] When an attack target is switched, by suspending this Tamer, ＜Draw 1＞ and 1 of your Digimon gets +2000 DP until the end of the turn.","-","-"],"card_number":"ST15-14","card_level":"R","image_link":"https://i.imgur.com/2wk3OgR.png","LOCAL_NUMBER":16257},
{"name":"용기의전진","color":"흑","type":"Opiton","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["While you have a Tamer with [Tai Kamiya] in its name, you may use this card without meeting its color requirements. [Main] Unsuspend 1 of your Digimon. Then, 1 of your Digimon with [Greymon] in its name isn't affected by the effects of your opponent's Digimon until the end of your opponent's turn.","-","-"],"card_number":"ST15-15","card_level":"U","image_link":"https://i.imgur.com/1oKOs1x.png","LOCAL_NUMBER":16258},
{"name":"트라이던트 암","color":"흑","type":"Opiton","attribute":"- -","dp":"-","cost":6,"evolution_cost":["-","-"],"effect":["[Main] ＜De-Digivolve 3＞ 1 of your opponent's Digimon. Then, until the end of your opponent's turn, 1 of your opponent's Digimon gains \"[Start of Your Main Phase] This Digimon attacks.\"","-","-"],"card_number":"ST15-16","card_level":"C","image_link":"https://i.imgur.com/wtR18Df.png","LOCAL_NUMBER":16259}]

ST16=[
{"name":"뿔몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST16-01","card_level":"U","image_link":"https://i.imgur.com/sIssMqX.png","LOCAL_NUMBER":16260},
{"name":"에렉몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Mammal","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[On Play] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand.","-","-"],"card_number":"ST16-02","card_level":"C","image_link":"https://i.imgur.com/3BIC5z0.png","LOCAL_NUMBER":16261},
{"name":"파피몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Reptile","dp":1000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["[Digivolve] [Tsunomon]: Cost 0[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.","-","-"],"card_number":"ST16-03","card_level":"R","image_link":"https://i.imgur.com/5pY8WIv.png","LOCAL_NUMBER":16262},
{"name":"테이파몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 백신 Holy Beast","dp":2000,"cost":3,"evolution_cost":["Lv.1~2","-"],"effect":["-","-","-"],"card_number":"ST16-04","card_level":"U","image_link":"https://i.imgur.com/sum9n2f.png","LOCAL_NUMBER":16263},
{"name":"울퉁몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Rock","dp":4000,"cost":4,"evolution_cost":["Lv.1~2","-"],"effect":["＜Retaliation＞ (When this Digimon is deleted in battle, delete the Digimon it battled.) [Your Turn] When this Digimon attacks an opponent's Digimon, lose 2 memory.","-","-"],"card_number":"ST16-05","card_level":"C","image_link":"https://i.imgur.com/zTFxLsj.png","LOCAL_NUMBER":16264},
{"name":"고스몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Ghost","dp":5000,"cost":4,"evolution_cost":["Lv.2~3","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST16-06","card_level":"C","image_link":"https://i.imgur.com/UdooJtO.png","LOCAL_NUMBER":16265},
{"name":"메라몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터 Flame","dp":6000,"cost":5,"evolution_cost":["Lv.2~3","-"],"effect":["[On Deletion] Gain 1 memory.","-","-"],"card_number":"ST16-07","card_level":"C","image_link":"https://i.imgur.com/KuJw6Hh.png","LOCAL_NUMBER":16266},
{"name":"가루몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 백신 Beast","dp":5000,"cost":6,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] Lv.3 w/[Gabumon] in name: Cost 2[Security] You may play 1 [Gabumon] or 1 Tamer card with [Matt Ishida] in its name from your hand or trash without paying the cost. [When Digivolving] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand.","-","-"],"card_number":"ST16-08","card_level":"SR","image_link":"https://i.imgur.com/ppsDxW1.png","LOCAL_NUMBER":16267},
{"name":"펌프몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 데이터 Puppet","dp":7000,"cost":6,"evolution_cost":["Lv.3~4","-"],"effect":["[On Play] You may play 1 purple level 3 Digimon card from your trash without paying the cost.","-","-"],"card_number":"ST16-09","card_level":"C","image_link":"https://i.imgur.com/WxMkikf.png","LOCAL_NUMBER":16268},
{"name":"맘몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 백신 Ancient Animal","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST16-10","card_level":"U","image_link":"https://i.imgur.com/219j0x9.png","LOCAL_NUMBER":16269},
{"name":"워가루몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 백신 Beastkin","dp":8000,"cost":8,"evolution_cost":["Lv.3~4","-"],"effect":["[Digivolve] Lv.4 w/[Garurumon] in name: Cost 3[When Attacking][Once Per Turn] By trashing 1 card in your hand, unsuspend this Digimon.","-","-"],"card_number":"ST16-11","card_level":"R","image_link":"https://i.imgur.com/RggzBH8.png","LOCAL_NUMBER":16270},
{"name":"메탈가루몬 ACE","color":"자","level":6,"type":"디지몬","attribute":"궁극체 데이터 Cyborg","dp":11000,"cost":6,"evolution_cost":["Lv.4~5","-"],"effect":["[Digivolve] Lv.5 w/[Garurumon] in name: Cost 3[Hand][Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) [When Digivolving] By trashing up to 3 cards in your hand, gain 1 memory for each card trashed. [When Attacking][Once Per Turn] By trashing 1 card in your hand, delete 1 of your opponent's Digimon with the lowest level.","-","-"],"card_number":"ST16-12","card_level":"SR","image_link":"https://i.imgur.com/dMm4dGI.png","LOCAL_NUMBER":16271},
{"name":"스컬맘몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 백신 Undead","dp":12000,"cost":11,"evolution_cost":["Lv.4~5","-"],"effect":["[When Digivolving] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand. [All Turns][Once Per Turn] When one of your effects trashes a card in your hand, you may play 1 level 4 or lower purple Digimon card from your trash without paying the cost.","-","-"],"card_number":"ST16-13","card_level":"U","image_link":"https://i.imgur.com/subkrCo.png","LOCAL_NUMBER":16272},
{"name":"매튜","color":"자","type":"테이머","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Start of Your Turn] If you have 2 or fewer memory, set it to 3. [All Turns] When one of your effects trashes a card in your hand, by suspending this Tamer, gain 1 memory.","-","-"],"card_number":"ST16-14","card_level":"R","image_link":"https://i.imgur.com/f9QtrQK.png","LOCAL_NUMBER":16273},
{"name":"우정의통곡","color":"자","type":"Opiton","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["While you have a Tamer with [Matt Ishida] in its name, you may use this card without meeting its color requirements.[Main] Return 1 Digimon card from your trash to the hand. Then, 1 of your Digimon with [Garurumon] in its name gains \"[On Deletion] Play this card without paying the cost\" until the end of your opponent's turn.","-","-"],"card_number":"ST16-15","card_level":"U","image_link":"https://i.imgur.com/fXulq8J.png","LOCAL_NUMBER":16274},
{"name":"볼 디블로","color":"자","type":"Opiton","attribute":"- -","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["[Main] Delete 1 of your opponent's level 5 or lower Digimon.","-","-"],"card_number":"ST16-16","card_level":"C","image_link":"https://i.imgur.com/GEpPTdj.png","LOCAL_NUMBER":16275}]

ST17=[
{"name":"구미몬","color":"녹","level":2,"type":"디지타마","attribute":"유년기 - Lesser","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST17-01","card_level":"U","image_link":"https://i.imgur.com/dfgiyfG.png","LOCAL_NUMBER":16276},
{"name":"테리어몬","color":"녹","level":3,"type":"디지몬","attribute":"성장기 백신 Beast","dp":1000,"cost":3,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] [Gummymon]: Cost 0[Main] [Once Per Turn] You may play 1 green Tamer card or 1 level 3 Digimon card with [Lopmon] in its name from your hand with the play cost reduced by 2.","-","-"],"card_number":"ST17-02","card_level":"SR","image_link":"https://i.imgur.com/CX96kpV.png","LOCAL_NUMBER":16277},
{"name":"로프몬","color":"녹","level":3,"type":"디지몬","attribute":"성장기 데이터 Beast","dp":1000,"cost":3,"evolution_cost":["Lv.2~3","-"],"effect":["[Digivolve] [Kokomon]: Cost 0[Main] [Once Per Turn] 1 of your Digimon gains ＜Alliance＞ for the turn.","-","-"],"card_number":"ST17-03","card_level":"SR","image_link":"https://i.imgur.com/OErKVHJ.png","LOCAL_NUMBER":16278},
{"name":"웬디몬","color":"녹자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Beastkin","dp":4000,"cost":5,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] Lv.3 w/[Terriermon]/[Lopmon] in name: Cost 2[On Play] [When Digivolving] Delete 1 level 3 or lower Digimon. If this effect deleted one of your Digimon, you may play 1 level 3 Digimon card with [Terriermon] or [Lopmon] in its name from your trash without paying the cost.","-","-"],"card_number":"ST17-04","card_level":"U","image_link":"https://i.imgur.com/sTKzU35.png","LOCAL_NUMBER":16279},
{"name":"가르고몬","color":"녹흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Beastkin","dp":5000,"cost":6,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] Lv.3 w/[Terriermon]/[Lopmon] in name: Cost 2[Your Turn] [Once Per Turn] When this Digimon becomes suspended, 1 of your Digimon gains ＜Jamming＞ for the turn.","-","-"],"card_number":"ST17-05","card_level":"C","image_link":"https://i.imgur.com/8QLkyRl.png","LOCAL_NUMBER":16280},
{"name":"래피드몬(아머체)","color":"녹황","level":4,"type":"디지몬","attribute":"Armor Form 백신 Holy Warrior","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] Lv.3 w/[Terriermon] in name: Cost 3＜Blocker＞ ＜Armor Purge＞ [All Turns] [Once Per Turn] When this Digimon becomes suspended, 1 of your opponent's Digimon and all of their Security Digimon get -4000 DP until the end of their turn.","-","-"],"card_number":"ST17-06","card_level":"SR","image_link":"https://i.imgur.com/RXEuaXo.png","LOCAL_NUMBER":16281},
{"name":"래피드몬","color":"녹흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","dp":7000,"cost":7,"evolution_cost":["Lv.4~5","Lv.3~4"],"effect":["[Digivolve] Lv.4 w/[Gargomon]/[Rapidmon] in name: Cost 3[On Play] [When Digivolving] ＜De-Digivolve 1＞ 1 of your opponent's Digimon. Then, if you have a green Tamer, until the end of your opponent's turn, your opponent's effects can't delete this Digimon or return it to the hand or deck.","-","-"],"card_number":"ST17-07","card_level":"C","image_link":"https://i.imgur.com/Mq3uwDR.png","LOCAL_NUMBER":16282},
{"name":"세인트가르고몬 ACE","color":"녹흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Machine","dp":12000,"cost":7,"evolution_cost":["Lv.5~6","Lv.4~5"],"effect":["[Digivolve] [Rapidmon] in name: Cost 5[Hand] [Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) ＜Blocker＞ ＜Reboot＞ [When Digivolving] Suspend 2 of your opponent's Digimon or Tamers. Then, 2 of their Digimon or Tamers can't unsuspend or digivolve until the end of their turn. [When Digivolving] [End of Attack] [Once Per Turn] You may unsuspend this Digimon.","-","-"],"card_number":"ST17-08","card_level":"SR","image_link":"https://i.imgur.com/f5wJzuX.png","LOCAL_NUMBER":16283},
{"name":"케루비몬(악)","color":"녹자","level":6,"type":"디지몬","attribute":"궁극체 백신 Cherub","dp":12000,"cost":12,"evolution_cost":["Lv.5~6","Lv.4~5"],"effect":["[Digivolve] [Antylamon]: Cost 3＜Alliance＞ [When Digivolving] You may delete 1 level 4 or lower Digimon. Then, you may play 1 level 4 or lower green or purple Digimon card from your hand or trash without paying the cost.","-","-"],"card_number":"ST17-09","card_level":"R","image_link":"https://i.imgur.com/EtMAJef.png","LOCAL_NUMBER":16284},
{"name":"곽소룡","color":"녹","type":"테이머","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory. [Main] By placing this Tamer and 1 [Gargomon] and 1 [Rapidmon] from your trash in any order as one of your [Terriermon]'s bottom digivolution cards, that Digimon may digivolve into [MegaGargomon] in the hand for a digivolution cost of 4, ignoring its digivolution requirements. If this effect digivolved, that Digimon gains ＜Rush＞ for the turn.","-","-"],"card_number":"ST17-10","card_level":"R","image_link":"https://i.imgur.com/71SodIj.png","LOCAL_NUMBER":16285},
{"name":"더블 타이푼","color":"녹","type":"옵션","attribute":"- -","dp":"-","cost":3,"evolution_cost":["-","-"],"effect":["[Main] Reveal the top 3 cards of your deck. Add 1 green Digimon card and 1 such Tamer card among them to the hand. Return the rest to the bottom of the deck. Then, place this card in the battle area. [Main] ＜Delay＞ ・ You may play 1 [Terriermon] or [Lopmon] from your hand without paying the cost.","-","-"],"card_number":"ST17-11","card_level":"R","image_link":"https://i.imgur.com/eiA9Jbv.png","LOCAL_NUMBER":16286},
{"name":"자이언트 미사일","color":"녹","type":"옵션","attribute":"- -","dp":"-","cost":8,"evolution_cost":["-","-"],"effect":["[Main] Suspend 1 of your opponent's Digimon. Then, return 1 of their suspended Digimon to the bottom of the deck. 1 of their Digimon can't unsuspend until the end of their turn.","-","-"],"card_number":"ST17-12","card_level":"U","image_link":"https://i.imgur.com/rFTrEi2.png","LOCAL_NUMBER":16287},
{"name":"매그너몬","color":"흑청","level":4,"type":"디지몬","attribute":"Armor Form 프리 Holy Warrior/Royal Knight","dp":7000,"cost":7,"evolution_cost":["Lv.3~4","Lv.2~3"],"effect":["[Digivolve] [Veemon]: Cost 3[Security] ＜De-Digivolve 1＞ 1 Digimon. At the end of the battle, 1 of your Digimon may digivolve into this card without paying the digivolution cost. ＜Blocker＞ ＜Armor Purge＞ [When Digivolving] Trash the top digivolution card of 1 of your opponent's Digimon for each of that Digimon's colors. Then, return 1 of your opponent's Digimon with no digivolution cards to the hand.","-","-"],"card_number":"ST17-13","card_level":"SR","image_link":"https://i.imgur.com/ScnynmD.png","LOCAL_NUMBER":16288}]

ST18=[
{"name":"플러피몬","color":"녹","level":2,"type":"디지타마","attribute":"幼年期 - 小鳥型/リベレイター","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【アタック時】[ターンに1回]このデジモンのDP以下の他のデジモン1体をレストできる。"],"card_number":"ST18-01","card_level":"C","image_link":"https://i.imgur.com/sps7yMq.png","LOCAL_NUMBER":16289},
{"name":"피요몬","color":"녹적","level":3,"type":"디지몬","attribute":"成長期 ワクチン種 ヒナ鳥型","dp":3000,"cost":3,"evolution_cost":["Lv.2~1","Lv.2~1"],"effect":["≪不屈≫（進化元を持つこのデジモンが消滅したとき、このカードをコストを支払わずに登場させる）","-","-"],"card_number":"ST18-02","card_level":"C","image_link":"https://i.imgur.com/uCCBO1Y.png","LOCAL_NUMBER":16290},
{"name":"팔코몬","color":"녹","level":3,"type":"디지몬","attribute":"成長期 ワクチン種 鳥型","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【アタック時】相手のデジモン1体をレストさせる。","-","-"],"card_number":"ST18-03","card_level":"C","image_link":"https://i.imgur.com/yzLBguR.png","LOCAL_NUMBER":16291},
{"name":"프테로몬","color":"녹","level":3,"type":"디지몬","attribute":"成長期 データ種 鳥竜型/リベレイター","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【登場時】自分のデッキの上から3枚オープンする。その中の特徴に「鳥」を含むカード1枚と特徴に「ヴォルテクスウォリアー」/「リベレイター」を持つカード1枚を手札に加える。残りはデッキの下に戻す。","-","【自分のターン】このデジモンをDP+2000。"],"card_number":"ST18-04","card_level":"R","image_link":"https://i.imgur.com/2slIDwx.png","LOCAL_NUMBER":16292},
{"name":"레드펭귄몬","color":"녹","level":3,"type":"디지몬","attribute":"成長期 データ種 鳥型","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【お互いのターン】[ターンに1回]このデジモンが効果でレストしたとき、相手のターン終了まで、特徴に「鳥」を含むか特徴に「ヴォルテクスウォリアー」を持つ自分のデジモン1体をDP+3000。","-","≪貫通≫（このデジモンがアタックしたバトルで相手のデジモンを消滅させたとき、アタック終了前にチェックする）"],"card_number":"ST18-05","card_level":"U","image_link":"https://i.imgur.com/p2kIpDm.png","LOCAL_NUMBER":16293},
{"name":"키위몬","color":"녹","level":4,"type":"디지몬","attribute":"成熟期 データ種 古代鳥型","dp":3000,"cost":3,"evolution_cost":["Lv.3~2","-"],"effect":["【登場時】【消滅時】相手のデジモン1体をレストさせる。〈ルール〉特徴:タイプ「植物型」を持つ。","-","-"],"card_number":"ST18-06","card_level":"C","image_link":"https://i.imgur.com/62cOXo6.png","LOCAL_NUMBER":16294},
{"name":"꼬끼몬","color":"녹","level":4,"type":"디지몬","attribute":"成熟期 データ種 巨鳥型","dp":4000,"cost":4,"evolution_cost":["Lv.3~2","-"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）","-","≪貫通≫（このデジモンがアタックしたバトルで相手のデジモンを消滅させたとき、アタック終了前にチェックする）"],"card_number":"ST18-07","card_level":"U","image_link":"https://i.imgur.com/hcVGahN.png","LOCAL_NUMBER":16295},
{"name":"게일몬","color":"녹","level":4,"type":"디지몬","attribute":"成熟期 データ種 鳥竜型/リベレイター","dp":6000,"cost":6,"evolution_cost":["Lv.3~2","-"],"effect":["【セキュリティ】自分の手札/トラッシュから、特徴に「リベレイター」を持つ登場コスト4以下のカード1枚をコストを支払わずに登場できる。≪ヴォルテクス≫（自分のターン終了時、このデジモンで相手のデジモンにアタックできる。この効果では、登場したターンでもアタックできる）","-","【自分のターン】このデジモンをDP+2000。"],"card_number":"ST18-08","card_level":"SR","image_link":"https://i.imgur.com/06ANs8S.png","LOCAL_NUMBER":16296},
{"name":"뿌띠몬","color":"녹","level":5,"type":"디지몬","attribute":"完全体 データ種 鳥型","dp":7000,"cost":6,"evolution_cost":["Lv.4~3","-"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【消滅時】自分の手札から、特徴に「鳥」/「植物型」を含むDP3000以下のデジモンカード1枚をコストを支払わずに登場できる。〈ルール〉特徴:タイプ「植物型」を持つ。","-","-"],"card_number":"ST18-09","card_level":"C","image_link":"https://i.imgur.com/eewtg85.png","LOCAL_NUMBER":16297},
{"name":"그랑게일몬","color":"녹","level":5,"type":"디지몬","attribute":"完全体 データ種 鳥竜型/ヴォルテクスウォリアー/リベレイター","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【登場時】【進化時】デジモン1体をレストさせる。この効果で自分のデジモンがレストしたなら、自分の手札から、特徴に「鳥」を含むDP3000以下のデジモンカード1枚をコストを支払わずに登場できる。","-","【自分のターン】[ターンに1回]このデジモンが相手のデジモンにアタックしたとき、このデジモンをアクティブにできる。"],"card_number":"ST18-10","card_level":"R","image_link":"https://i.imgur.com/8zXRERp.png","LOCAL_NUMBER":16298},
{"name":"패롯몬","color":"녹","level":5,"type":"디지몬","attribute":"完全体 ワクチン種 巨鳥型","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【登場時】相手のデジモン1体をレストさせる。その後、相手のターン終了まで、相手のデジモン1体はアクティブにならない。","-","≪貫通≫（このデジモンがアタックしたバトルで相手のデジモンを消滅させたとき、アタック終了前にチェックする）"],"card_number":"ST18-11","card_level":"U","image_link":"https://i.imgur.com/sP9uL62.png","LOCAL_NUMBER":16299},
{"name":"제퍼가몬","color":"녹","level":6,"type":"디지몬","attribute":"究極体 データ種 魔法騎士型/ヴォルテクスウォリアー/リベレイター","dp":11000,"cost":11,"evolution_cost":["Lv.5~3","-"],"effect":["≪ヴォルテクス≫（自分のターン終了時、このデジモンで相手のデジモンにアタックできる。この効果では、登場したターンでもアタックできる）【進化時】デジモン1体をレストさせる。その後、デジモン1体をアクティブにする。【お互いのターン】[ターンに1回]デジモンがアクティブになったとき、ターン終了まで、このデジモンは相手のデジモンの効果を受けず、DP+3000。〈ルール〉特徴:タイプ「鳥竜型」を持つ。","-","-"],"card_number":"ST18-12","card_level":"SR","image_link":"https://i.imgur.com/Ouu5B4A.png","LOCAL_NUMBER":16300},
{"name":"크로스몬","color":"녹","level":6,"type":"디지몬","attribute":"究極体 ワクチン種 巨鳥型","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["≪不屈≫（進化元を持つこのデジモンが消滅したとき、このカードをコストを支払わずに登場させる）【登場時】【進化時】レスト状態の相手のデジモン1体を手札に戻す。","-","-"],"card_number":"ST18-13","card_level":"U","image_link":"https://i.imgur.com/V1m4T4L.png","LOCAL_NUMBER":16301},
{"name":"카자마 쇼토","color":"녹","level":"-","type":"테이머","attribute":"- - リベレイター","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["【自分のターン開始時】メモリーが2以下なら、3にする。【自分のターン】自分のデジモンが相手のデジモンにアタックしたとき、このテイマーをレストさせることで、アタックの対象を他の相手のデジモンかプレイヤーに変更する。","【セキュリティ】このカードをコストを支払わずに登場させる。","-"],"card_number":"ST18-14","card_level":"R","image_link":"https://i.imgur.com/OKQ05dK.png","LOCAL_NUMBER":16302},
{"name":"아네모이 엠브레이스","color":"녹","level":"-","type":"옵션","attribute":"- - リベレイター","dp":"-","cost":5,"evolution_cost":["-","-"],"effect":["【メイン】デジモン1体をレストさせる。この効果で自分のデジモンがレストしたなら、レスト状態の相手のデジモン1体をデッキの下に戻す。その後、デジモン1体をアクティブにする。","【セキュリティ】レスト状態の相手のデジモン1体をデッキの下に戻す。","-"],"card_number":"ST18-15","card_level":"U","image_link":"https://i.imgur.com/5ISD81e.png","LOCAL_NUMBER":16303}]



ST19=[
{"name":"캬로몬","color":"황","level":2,"type":"디지타마","attribute":"幼年期 - レッサー型/リベレイター","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【アタック時】[ターンに1回]他の自分のデジモンがいるなら、≪1ドロー≫（自分のデッキからカードを1枚引く）。"],"card_number":"ST19-01","card_level":"C","image_link":"https://i.imgur.com/GXKBHK5.png","LOCAL_NUMBER":16304},
{"name":"정크몬","color":"황","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["≪デコイ《特徴「パペット型」》≫（特徴に「パペット型」を持つ他の自分のデジモンが相手の効果で消滅するとき、このデジモンを消滅させることで、そのデジモン1体は消滅しない）","-","≪防壁≫（このデジモンがバトルで消滅するとき、自分のセキュリティを上から1枚破棄することで、消滅しない）"],"card_number":"ST19-02","card_level":"U","image_link":"https://i.imgur.com/NVsmrI0.png","LOCAL_NUMBER":16305},
{"name":"슈몬","color":"황","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型/リベレイター","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【登場時】自分のデッキの上から3枚オープンする。その中の特徴に「パペット型」を持つカード1枚と特徴に「リベレイター」を持つカード1枚を手札に加える。残りはデッキの下に戻す。","-","【自分のターン】相手のセキュリティデジモン全てをDP-3000。"],"card_number":"ST19-03","card_level":"R","image_link":"https://i.imgur.com/19Fn7FB.png","LOCAL_NUMBER":16306},
{"name":"폰체스몬(백)","color":"황흑","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型","dp":2000,"cost":3,"evolution_cost":["Lv.2~1","Lv.2~1"],"effect":["【登場時】自分の手札から、特徴に「パペット型」を持つカード1枚を破棄することで、≪2ドロー≫（自分のデッキからカードを2枚引く）。","-","≪再起動≫（このデジモンは相手のアクティブフェイズでもアクティブになる）"],"card_number":"ST19-04","card_level":"C","image_link":"https://i.imgur.com/VEDUM4J.png","LOCAL_NUMBER":16307},
{"name":"폰체스몬(흑)","color":"흑황","level":3,"type":"디지몬","attribute":"成長期 ウィルス種 パペット型","dp":2000,"cost":3,"evolution_cost":["Lv.2~1","Lv.2~1"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【消滅時】自分の手札から、特徴に「パペット型」を持つカード1枚を破棄することで、≪2ドロー≫（自分のデッキからカードを2枚引く）。","-","-"],"card_number":"ST19-05","card_level":"C","image_link":"https://i.imgur.com/DxtYocv.png","LOCAL_NUMBER":16308},
{"name":"도그몬","color":"황","level":4,"type":"디지몬","attribute":"成熟期 データ種 パペット型","dp":4000,"cost":4,"evolution_cost":["Lv.3~2","-"],"effect":["【登場時】【消滅時】相手のターン終了まで、相手のデジモン1体に≪Sアタック-1≫（このデジモンがチェックする枚数-1）を与える。","-","-"],"card_number":"ST19-06","card_level":"C","image_link":"https://i.imgur.com/CDLHUvL.png","LOCAL_NUMBER":16309},
{"name":"토브캐트몬","color":"황","level":4,"type":"디지몬","attribute":"成熟期 データ種 パペット型/X抗体","dp":5000,"cost":5,"evolution_cost":["Lv.3~2","-"],"effect":["≪ジャミング≫（このデジモンはセキュリティデジモンとのバトルでは消滅しない）","-","≪防壁≫（このデジモンがバトルで消滅するとき、自分のセキュリティを上から1枚破棄することで、消滅しない）"],"card_number":"ST19-07","card_level":"U","image_link":"https://i.imgur.com/DGrVvlh.png","LOCAL_NUMBER":16310},
{"name":"슈슈몬","color":"황","level":4,"type":"디지몬","attribute":"成熟期 ウィルス種 パペット型/リベレイター","dp":5000,"cost":6,"evolution_cost":["Lv.3~2","-"],"effect":["【セキュリティ】自分の手札/トラッシュから、特徴に「リベレイター」を持つ登場コスト4以下のカード1枚をコストを支払わずに登場できる。≪オーバークロック《特徴「パペット型」》≫（自分のターン終了時、自分のトークンか特徴に「パペット型」を持つ他の自分のデジモン1体を消滅させることで、このデジモンでレストせずにプレイヤーにアタックする）","-","【自分のターン】相手のセキュリティデジモン全てをDP-3000。"],"card_number":"ST19-08","card_level":"SR","image_link":"https://i.imgur.com/FHGLMez.png","LOCAL_NUMBER":16311},
{"name":"팬더몬","color":"황","level":5,"type":"디지몬","attribute":"完全体 データ種 パペット型","dp":7000,"cost":6,"evolution_cost":["Lv.4~3","-"],"effect":["≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【消滅時】自分の手札から、特徴に「パペット型」を持つLv.3のデジモンカード1枚をコストを支払わずに登場できる。","-","-"],"card_number":"ST19-09","card_level":"C","image_link":"https://i.imgur.com/Ii0oUqL.png","LOCAL_NUMBER":16312},
{"name":"엑스티라노몬","color":"황녹","level":5,"type":"디지몬","attribute":"完全体 ワクチン種 パペット型","dp":7000,"cost":7,"evolution_cost":["Lv.4~4","Lv.4~4"],"effect":["名称に「ティラノモン」/「レアモン」を含むLv.4:コスト3≪アーマー解除≫（このデジモンが消滅するとき、このデジモンに重ねられているカードを上から1枚破棄することで、消滅しない）名称に「ティラノモン」/「レアモン」を含むLv.4×特徴に「パペット型」を持つLv.4","-","≪防壁≫（このデジモンがバトルで消滅するとき、自分のセキュリティを上から1枚破棄することで、消滅しない）"],"card_number":"ST19-10","card_level":"U","image_link":"https://i.imgur.com/HKk4lDY.png","LOCAL_NUMBER":16313},
{"name":"샤프로몬","color":"황","level":5,"type":"디지몬","attribute":"完全体 ウィルス種 パペット型/リベレイター","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【登場時】【進化時】ターン終了まで、相手のデジモン1体をDP-3000。デジモンが3体以上いるなら、このDPマイナス効果の数値-3000。","-","【お互いのターン】[ターンに1回]このデジモンが自分の効果以外でバトルエリアを離れるとき、自分のトークンか特徴に「パペット型」を持つ他の自分のデジモン1体を消滅させることで、離れない。"],"card_number":"ST19-11","card_level":"R","image_link":"https://i.imgur.com/n9rLfGy.png","LOCAL_NUMBER":16314},
{"name":"상드리몬","color":"황","level":6,"type":"디지몬","attribute":"究極体 ウィルス種 パペット型/リベレイター","dp":11000,"cost":11,"evolution_cost":["Lv.5~3","-"],"effect":["≪オーバークロック《特徴「パペット型」》≫（自分のターン終了時、自分のトークンか特徴に「パペット型」を持つ他の自分のデジモン1体を消滅させることで、このデジモンでレストせずにプレイヤーにアタックする）≪ブロッカー≫（このデジモンはブロックタイミングでブロックできる）【進化時】「使い魔」（デジモン・黄・DP3000・【消滅時】ターン終了まで、相手のデジモン1体をDP-3000。）トークン2体を登場できる。","-","-"],"card_number":"ST19-12","card_level":"SR","image_link":"https://i.imgur.com/1PT2tFb.png","LOCAL_NUMBER":16315},
{"name":"신퍼펫몬","color":"황","level":6,"type":"디지몬","attribute":"究極体 ワクチン種 パペット型","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["名称に「もんざえモン」/「ヌメモン」を含むLv.5:コスト3≪アーマー解除≫（このデジモンが消滅するとき、このデジモンに重ねられているカードを上から1枚破棄することで、消滅しない）【登場時】【進化時】自分のトラッシュから、名称に「ヌメモン」を含むか特徴に「パペット型」を持つLv.5以下のカード1枚をこのデジモンの進化元の下に置くことで、≪リカバリー+1《デッキ》≫（自分のデッキの上から1枚をセキュリティの上に置く）。","-","-"],"card_number":"ST19-13","card_level":"U","image_link":"https://i.imgur.com/I0vH7if.png","LOCAL_NUMBER":16316},
{"name":"키노사키 아리사","color":"황","level":"-","type":"테이머","attribute":"- - リベレイター","dp":"-","cost":4,"evolution_cost":["-","-"],"effect":["【自分のターン開始時】メモリーが2以下なら、3にする。【自分のターン】自分のトークンか特徴に「パペット型」を持つ自分のデジモンが効果で登場したとき、このテイマーをレストさせることで、ターン終了まで、そのデジモン1体は≪速攻≫（このデジモンは登場したターンでもアタックできる）を得る。","【セキュリティ】このカードをコストを支払わずに登場させる。","-"],"card_number":"ST19-14","card_level":"R","image_link":"https://i.imgur.com/fY8AHdN.png","LOCAL_NUMBER":16317},
{"name":"노블 패밀리아츠","color":"황","level":"-","type":"옵션","attribute":"- - リベレイター","dp":"-","cost":5,"evolution_cost":["-","-"],"effect":["【メイン】ターン終了まで、相手のデジモン1体をDP-6000。デジモンが3体以上いるなら、このDPマイナス効果の数値-6000。","【セキュリティ】このカードの【メイン】効果を発揮する。","-"],"card_number":"ST19-15","card_level":"U","image_link":"https://i.imgur.com/aqXoqem.png","LOCAL_NUMBER":16318}
]