
ST13=
[
{"name":"사쿳토몬","color":"흑","level":2,"type":"디지타마","attribute":"유년기 - Weapon","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST13-01","card_level":"U","image_link":"https://i.imgur.com/yTQKOS3.png","LOCAL_NUMBER":16216},
{"name":"즈바몬","color":"적","level":3,"type":"디지몬","attribute":"성장기 백신 Weapon/Legend-Arms","cost":3,"evolution_cost":["0 from Lv.2","Black"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's black or has [Legend-Arms] in its traits as its bottom digivolution card, you may reveal the top card of your deck. If that card is a Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less, you may play it without paying its memory cost. Add the rest to your hand.","-","-"],"card_number":"ST13-02","card_level":"U","image_link":"https://i.imgur.com/cWn3RTs.png","LOCAL_NUMBER":16217},
{"name":"즈바이거몬","color":"적","level":4,"type":"디지몬","attribute":"성숙기 백신 Weapon/Legend-Arms","cost":5,"evolution_cost":["2 from Lv.3","Black"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's black or has [Legend-Arms] in its traits as its bottom digivolution card, delete 1 of your opponent's Digimon with 5000 DP or less.","-","-"],"card_number":"ST13-03","card_level":"C","image_link":"https://i.imgur.com/fOocrOy.png","LOCAL_NUMBER":16218},
{"name":"듀라몬","color":"적","level":5,"type":"디지몬","attribute":"완전체 백신 Weapon/Legend-Arms","cost":7,"evolution_cost":["3 from Lv.4","Black"],"effect":["[Your Turn] When this Digimon would digivolve into a card in your hand that's black or has [Legend-Arms] in its traits, reduce the digivolution cost by 1.","-","-"],"card_number":"ST13-04","card_level":"U","image_link":"https://i.imgur.com/s0svzhS.png","LOCAL_NUMBER":16219},
{"name":"듀란다몬","color":"적","level":6,"type":"디지몬","attribute":"궁극체 백신 Holy Sword/Legend-Arms","cost":11,"evolution_cost":["3 from Lv.5","Black"],"effect":["[Your Turn][Once Per Turn] When one of your effects places a digivolution card under this Digimon, this Digimon gets +3000 DP and ＜Security Attack +1＞ for the turn. (This Digimon checks 1 additional security card.)[When Attacking] Reveal the top 3 cards of your deck. You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less among them without paying its memory cost. Place the rest at the bottom of your deck in any order.","-","-"],"card_number":"ST13-05","card_level":"SR","image_link":"https://i.imgur.com/i871B2m.png","LOCAL_NUMBER":16220},
{"name":"라그나로드몬","color":"적흑","level":7,"type":"디지몬","attribute":"궁극체 바이러스 Unique/Legend-Arms","cost":15,"evolution_cost":["6 from Lv.6","Black"],"effect":["DNA Digivolution: 0 from red Lv.6 + black Lv.6[When Digivolving] ＜Blitz＞ (This Digimon can attack when your opponent has 1 or more memory.) When DNA digivolving, for every 4 cards in this Digimon's digivolution cards, delete 1 of your opponent's Digimon with a play cost of 20 or less and trash the top card of your opponent's security stack.[All Turns][Once Per Turn] When a card is removed from a player's security stack, unsuspend this Digimon.","-","-"],"card_number":"ST13-06","card_level":"SR","image_link":"https://i.imgur.com/6HivZmd.png","LOCAL_NUMBER":16221},
{"name":"코테몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 데이터 Reptile","cost":2,"evolution_cost":["0 from Lv.2","-"],"effect":["-","-","-"],"card_number":"ST13-07","card_level":"C","image_link":"https://i.imgur.com/YbXcXeY.png","LOCAL_NUMBER":16222},
{"name":"치쿠리몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 바이러스 Mine","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[All Turns] Players can't reduce play costs.","-","-"],"card_number":"ST13-08","card_level":"C","image_link":"https://i.imgur.com/JMyKk1m.png","LOCAL_NUMBER":16223},
{"name":"루도몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 데이터 Armor/Legend-Arms","cost":3,"evolution_cost":["0 from Lv.2","Red"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's red or has [Legend-Arms] in its traits as its bottom digivolution card, you may reveal the top card of your deck. You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less among them without paying its memory cost. Add the rest to your hand.","-","-"],"card_number":"ST13-09","card_level":"U","image_link":"https://i.imgur.com/Sd2gpdj.png","LOCAL_NUMBER":16224},
{"name":"그라디몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Warrior","cost":4,"evolution_cost":["1 from Lv.3","-"],"effect":["-","-","-"],"card_number":"ST13-10","card_level":"C","image_link":"https://i.imgur.com/tilT8MA.png","LOCAL_NUMBER":16225},
{"name":"티아루도몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 데이터 Armor/Legend-Arms","cost":5,"evolution_cost":["2 from Lv.3","Red"],"effect":["[On Play] By placing this Digimon under 1 of your other Digimon that's red or has [Legend-Arms] in its traits as its bottom digivolution card, 1 of your Digimon gains ＜Reboot＞ until the end of your opponent's turn. (Unsuspend this Digimon during your opponent's unsuspend phase.)","-","-"],"card_number":"ST13-11","card_level":"U","image_link":"https://i.imgur.com/TyHmGaK.png","LOCAL_NUMBER":16226},
{"name":"나이트몬","color":"흑적","level":5,"type":"디지몬","attribute":"완전체 데이터 Warrior","cost":5,"evolution_cost":["3 from Lv.4","Red"],"effect":["-","-","-"],"card_number":"ST13-12","card_level":"C","image_link":"https://i.imgur.com/ZS7STAZ.png","LOCAL_NUMBER":16227},
{"name":"라이지루도몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Armor/Legend-Arms","cost":7,"evolution_cost":["3 from Lv.4","Red"],"effect":["[Opponent's Turn] This Digimon can't be deleted by your opponent's effects.","-","-"],"card_number":"ST13-13","card_level":"R","image_link":"https://i.imgur.com/kWCbL3O.png","LOCAL_NUMBER":16228},
{"name":"브리웨루드라몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 데이터 Armor/Legend-Arms","cost":11,"evolution_cost":["4 from Lv.5","Red"],"effect":["[Your Turn][Once Per Turn] When one of your effects places a digivolution card under this Digimon, your opponent's effects can't delete this Digimon or return it to its owner's hand or deck until the end of their turn.[When Digivolving] Reveal the top 3 cards of your deck. You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less among them without paying its memory cost. Place the rest at the bottom of your deck in any order.","-","-"],"card_number":"ST13-14","card_level":"R","image_link":"https://i.imgur.com/0MxhpyD.png","LOCAL_NUMBER":16229},
{"name":"다이렉트 스매셔","color":"적","type":"옵션","attribute":"- -","cost":7,"evolution_cost":["-","-"],"effect":["While you have a Digimon with [Legend-Arms] in its traits in play, you may use this card without meeting its color requirements.[Main] Delete 1 of your opponent's Digimon with the highest DP.","-","-"],"card_number":"ST13-15","card_level":"R","image_link":"https://i.imgur.com/SLOyILr.png","LOCAL_NUMBER":16230},
{"name":"모순공투","color":"흑적","type":"옵션","attribute":"- Legend-Arms","cost":4,"evolution_cost":["-","-"],"effect":["[Main] You may play 1 Digimon card with [Legend-Arms] in its traits and a play cost of 7 or less in your hand without paying its memory cost. Then, place this card in your Battle Area.[Main] ＜Delay＞ (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.)・Reveal the top 4 cards of your deck. Place those cards on the top or bottom of your deck in any order.","-","-"],"card_number":"ST13-16","card_level":"C","image_link":"https://i.imgur.com/zF7pBl1.png","LOCAL_NUMBER":16231}
]