
ST14=
[
    {"name":"야몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - Lesser","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST14-01","card_level":"U","image_link":"https://i.imgur.com/as9gqk9.png","LOCAL_NUMBER":16232},
{"name":"임프몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Evil","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[When Attacking] If you have 20 or more cards in your trash, this Digimon may digivolve into [Beelzemon] from your trash for a digivolution cost of 3, ignoring its digivolution requirements.","-","-"],"card_number":"ST14-02","card_level":"SR","image_link":"https://i.imgur.com/gMjEWeK.png","LOCAL_NUMBER":16233},
{"name":"캔들몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Flame","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[On Play] Trash the top 2 cards of your deck.[On Deletion] If you have 10 or more cards in your trash, ＜Draw 1＞. (Draw 1 card from your deck.)","-","-"],"card_number":"ST14-03","card_level":"U","image_link":"https://i.imgur.com/7QtY3Bv.png","LOCAL_NUMBER":16234},
{"name":"파스코몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Dark Animal","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["＜Blocker＞ (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[Your Turn] This Digimon can't attack players.","-","-"],"card_number":"ST14-04","card_level":"C","image_link":"https://i.imgur.com/RFX0yM8.png","LOCAL_NUMBER":16235},
{"name":"포큐파몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Puppet","cost":4,"evolution_cost":["2 from Lv.3","-"],"effect":["＜Blocker＞ (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.) [On Play] Trash the top 2 cards of your deck.","-","-"],"card_number":"ST14-05","card_level":"C","image_link":"https://i.imgur.com/HKe3i7p.png","LOCAL_NUMBER":16236},
{"name":"위치몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터 Wizard","cost":5,"evolution_cost":["2 from Lv.3","-"],"effect":["[When Digivolving] Trash the top 3 cards of your deck.","-","-"],"card_number":"ST14-06","card_level":"U","image_link":"https://i.imgur.com/gICncKF.png","LOCAL_NUMBER":16237},
{"name":"바알몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 프리 Wizard","cost":7,"evolution_cost":["3 from Lv.4","-"],"effect":["[When Digivolving] Trash the top 3 cards of your deck.[When Digivolving] This Digimon gains \"[On Deletion] If there are 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying the cost\" until the end of your opponent's turn.","-","-"],"card_number":"ST14-07","card_level":"R","image_link":"https://i.imgur.com/wuQHQRp.png","LOCAL_NUMBER":16238},
{"name":"베르제브몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스 Demon Lord/Seven Great Demon Lords","cost":12,"evolution_cost":["4 from Lv.5","-"],"effect":["[When Digivolving] Trash the top 4 cards of your deck. [All Turns][Once Per Turn] When a card is trashed from your deck, gain 1 memory for every 10 cards in your trash.[Your Turn][Once Per Turn] When a card is trashed from your deck, this Digimon gains ＜Security Attack +1＞ (This Digimon checks 1 additional security card) for the turn.","-","-"],"card_number":"ST14-08","card_level":"SR","image_link":"https://i.imgur.com/qEof3bp.png","LOCAL_NUMBER":16239},
{"name":"베르스타몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스 Wizard/Three Musketeers","cost":13,"evolution_cost":["3 from Lv.5","-"],"effect":["When you would play this card from your hand, reduce the play cost by 4 for every 10 cards in your trash.[All Turns][Once Per Turn] When a card is trashed from your deck, you may play 1 [Impmon] from your trash without paying the cost. The Digimon played by this effect gains ＜Rush＞ for the turn.[Opponent's Turn] When an opponent's Digimon attacks, trash the top card of your deck.","-","-"],"card_number":"ST14-09","card_level":"SR","image_link":"https://i.imgur.com/xksYDWz.png","LOCAL_NUMBER":16240},
{"name":"베르제브몬:블래스트 모드","color":"자","level":7,"type":"디지몬","attribute":"궁극체 바이러스 Demon Lord","cost":14,"evolution_cost":["4 from Lv.6","-"],"effect":["When this card is trashed from your deck, delete 1 of your opponent's level 3 or lower Digimon. For every 10 cards in your trash, add 1 to the maximum level of the Digimon you can choose with this effect. [When Digivolving] Unsuspend this Digimon. If you have 20 or more cards in your trash, gain 3 memory.","-","-"],"card_number":"ST14-10","card_level":"SR","image_link":"https://i.imgur.com/ocVRExR.png","LOCAL_NUMBER":16241},
{"name":"다영 & 진","color":"자","type":"테이머","attribute":"- -","cost":3,"evolution_cost":["-","-"],"effect":["[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with [Evil], [Wizard], or [Demon Lord] in its traits among them to your hand. Place the rest at the bottom of your deck in any order. [Your Turn] When one of your Digimon digivolves into a purple Digimon, you may suspend this Tamer and return 1 card from your hand to your deck to gain 1 memory.","-","-"],"card_number":"ST14-11","card_level":"R","image_link":"https://i.imgur.com/yRhS0ef.png","LOCAL_NUMBER":16242},
{"name":"견원의흉탄","color":"자","type":"옵션","attribute":"- -","cost":7,"evolution_cost":["-","-"],"effect":["When this card is trashed from your deck, you may place it in the battle area.  [Main] Delete 1 of your opponent's Digimon with the highest level. [Main]  ＜Delay＞ (After this card is placed, by trashing it the next turn or later, activate the effect below.) ・Return 1 purple Digimon card or Tamer card from your trash to your hand.","-","-"],"card_number":"ST14-12","card_level":"R","image_link":"https://i.imgur.com/b94gOAp.png","LOCAL_NUMBER":16243}
]
