
ST14=
[{"name":"임프몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스종 소악마형","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【어택 시】자신의 트래시가 20장 이상이라면, 이 디지몬을 자신의 트래시의 「베르제브몬」으로 진화조건을 무시하고 진화 코스트 3으로 진화시킬 수 있다.","-","【자신의 턴】[턴에 1회]자신의 덱이 파기되었을 때, Lv.3의 상대의 디지몬 1마리를 소멸시킨다."],"card_number":"ST14-02","card_level":"SR","image_link":"https://i.imgur.com/tQzFvNV.png"},
{"name":"야몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - 렛서형","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["-","-","【어택 시】[턴에 1회]이 디지몬이 특징으로 「마인형」/「마왕형」을 가진다면, 자신의 덱 위에서부터 2장 파기한다."],"card_number":"ST14-01","card_level":"U","image_link":"https://i.imgur.com/6M0ldpa.png"},
{"name":"캔들몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터종 화염형","dp":1000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["【등장 시】자신의 덱 위에서부터 2장 파기한다. 【소멸 시】자신의 트래시가 10장 이상이라면 , 《1 드로우》(자신의 덱에서 카드를 1장 뽑는다).","-","-"],"card_number":"ST14-03","card_level":"U","image_link":"https://i.imgur.com/4MmtMWr.png"},
{"name":"파스코몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스종 마수형","dp":2000,"cost":3,"evolution_cost":["Lv.2~0","-"],"effect":["《블로커》(이 디지몬은 블록 타이밍에 블록할 수 있다) 【자신의 턴】이 디지몬은 플레이어에게 어택할 수 없다.","-","-"],"card_number":"ST14-04","card_level":"C","image_link":"https://i.imgur.com/jPkP6dl.png"},
{"name":"포큐파몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스종 퍼펫형","dp":4000,"cost":4,"evolution_cost":["Lv.3~2","-"],"effect":["《블로커》(이 디지몬은 블록 타이밍에 블록할 수 있다) 【등장 시】자신의 덱 위에서부터 2장 파기한다.","-","-"],"card_number":"ST14-05","card_level":"C","image_link":"https://i.imgur.com/dyDynKA.png"},
{"name":"위치몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터종 마인형","dp":5000,"cost":5,"evolution_cost":["Lv.3~2","-"],"effect":["【진화 시】자신의 덱 위에서부터 3장 파기한다.","-","【자신의 턴】특징으로 「마인형」/「마왕형」을 가진 이 디지몬을 DP +2000."],"card_number":"ST14-06","card_level":"U","image_link":"https://i.imgur.com/x3UI3kB.png"},
{"name":"바알몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 프리 마인형","dp":7000,"cost":7,"evolution_cost":["Lv.4~3","-"],"effect":["【진화 시】자신의 덱 위에서부터 3장 파기한다. 【진화 시】상대의 턴 종료까지 이 디지몬은 「【소멸 시】자신의 트래시가 10장 이상이라면, 자신의 트래시에서 「베르제브몬」 1장을 코스트를 지불하지 않고 등장시킬 수 있다.」의 효과를 얻는다.","-","【자신의 턴】특징으로 「마인형」/「마왕형」을 가진 이 디지몬을 DP +2000."],"card_number":"ST14-07","card_level":"R","image_link":"https://i.imgur.com/t8tUIZW.png"},
{"name":"베르제브몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스종 마왕형,7대마왕","dp":12000,"cost":12,"evolution_cost":["Lv.5~4","-"],"effect":["【진화 시】자신의 덱 위에서부터 4장 파기한다. 【서로의 턴】[턴에 1회]자신의 덱이 파기되었을 때, 자신의 트래시 10장마다, 메모리 +1. 【자신의 턴】[턴에 1회]자신의 덱이 파기되었을 때, 턴 종료까지 이 디지몬은 《S 어택 +1》(이 디지몬이 체크하는 매수 +1)을 얻는다.","-","-"],"card_number":"ST14-08","card_level":"SR","image_link":"https://i.imgur.com/AAXOERb.png"},
{"name":"베르스타몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 바이러스종 마인형,3총사","dp":11000,"cost":13,"evolution_cost":["Lv.5~3","-"],"effect":["패의 이 카드가 등장할 때, 자신의 트래시 10장마다 지불하는 등장 코스트 -4. 【서로의 턴】[턴에 1회]자신의 덱이 파기되었을 때, 자신의 트래시에서 「임프몬」 1장을 코스트를 지불하지 않고 등장시킬 수 있다. 턴 종료까지 이 효과로 등장한 디지몬은 《속공》을 얻는다. 【상대의 턴】상대의 디지몬이 어택했을 때, 자신의 덱 위에서부터 1장 파기한다.","-","-"],"card_number":"ST14-09","card_level":"SR","image_link":"https://i.imgur.com/0fTI9Pw.png"},
{"name":"베르제브몬: 블래스트 모드","color":"자","level":7,"type":"디지몬","attribute":"궁극체 바이러스종 마왕형","dp":14000,"cost":14,"evolution_cost":["Lv.6~4","-"],"effect":["이 카드가 덱에서 파기되었을 때, Lv.3 이하의 상대의 디지몬 1마리를 소멸시킨다. 자신의 트래시 10장마다 이 효과로 선택할 수 있는 Lv. 상한 +1. 【진화 시】이 디지몬을 액티브로 한다. 자신의 트래시가 20장 이상이라면, 메모리 +3.","-","-"],"card_number":"ST14-10","card_level":"SR","image_link":"https://i.imgur.com/mWbnToO.png"},
{"name":"다영&진","color":"자","level":"-","type":"테이머","attribute":"- - -","dp":"-","cost":"-","evolution_cost":["-","-"],"effect":["【등장 시】자신의 덱 위에서부터 4장 오픈한다. 그중 특징으로 「소악마형」/「마인형」/「마왕형」을 가진 디지몬 카드 1장을 패에 추가한다. 나머지는 덱 아래로 되돌린다. 【자신의 턴】자신의 디지몬이 퍼플인 디지몬으로 진화했을 때, 이 테이머를 레스트시키는 것으로, 자신의 패 1장을 덱 위로 되돌리고, 메모리 +1.","【시큐리티】이 카드를 코스트를 지불하지 않고 등장시킨다.","-"],"card_number":"ST14-11","card_level":"R","image_link":"https://i.imgur.com/fywvJWS.png"},
{"name":"견원의 흉탄","color":"자","level":"-","type":"옵션","attribute":"- - -","dp":"-","cost":7,"evolution_cost":["-","-"],"effect":["이 카드가 덱에서 파기되었을 때, 이 카드를 배틀 에어리어에 놓을 수 있다. 【메인】가장 Lv.이 높은 상대의 디지몬 1마리를 소멸시킨다. 【메인】《딜레이》(놓인 다음 턴 이후에 이 카드를 파기하는 것으로, 효과를 발휘한다) ・자신의 트래시에서 퍼플인 디지몬 카드/테이머 카드 1장을 패로 되돌린다.","【시큐리티】가장 Lv.이 높은 상대의 디지몬 1마리를 소멸시킨다.","-"],"card_number":"ST14-12","card_level":"R","image_link":"https://i.imgur.com/Byc61OS.png"},
]
