
ST15=
[

    {"name":"코로몬","color":"흑","level":2,"type":"디지타마","attribute":"유년기 - Lesser","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST15-01","card_level":"U","image_link":"https://i.imgur.com/swxQ1g6.png","LOCAL_NUMBER":16244},
{"name":"아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Reptile","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[Digivolve][Koromon]: Cost 0[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.","-","-"],"card_number":"ST15-02","card_level":"R","image_link":"https://i.imgur.com/dKh8VPd.png","LOCAL_NUMBER":16245},
{"name":"투명아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["-","-","-"],"card_number":"ST15-03","card_level":"U","image_link":"https://i.imgur.com/Q1WJCmk.png","LOCAL_NUMBER":16246},
{"name":"솔라몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Machine","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[On Play] Reveal the top card of your deck. If it's a black card, add it to your hand. Trash the rest.","-","-"],"card_number":"ST15-04","card_level":"C","image_link":"https://i.imgur.com/qMzljxS.png","LOCAL_NUMBER":16247},
{"name":"토이아구몬","color":"흑","level":3,"type":"디지몬","attribute":"성장기 백신 Puppet","cost":4,"evolution_cost":["0 from Lv.2","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.) [Your Turn] When this Digimon attacks a player, lose 2 memory.","-","-"],"card_number":"ST15-05","card_level":"C","image_link":"https://i.imgur.com/Cfx2Aye.png","LOCAL_NUMBER":16248},
{"name":"메카노몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Machine","cost":4,"evolution_cost":["2 from Lv.3","-"],"effect":["-","-","-"],"card_number":"ST15-06","card_level":"C","image_link":"https://i.imgur.com/XPxgXXs.png","LOCAL_NUMBER":16249},
{"name":"탱크몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 데이터 Cyborg","cost":5,"evolution_cost":["2 from Lv.3","-"],"effect":["＜Jamming＞ (This Digimon can't be deleted in battles against Security Digimon.)","-","-"],"card_number":"ST15-07","card_level":"C","image_link":"https://i.imgur.com/9laXQIr.png","LOCAL_NUMBER":16250},
{"name":"그레이몬","color":"흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Dinosaur","cost":6,"evolution_cost":["2 from Lv.3","-"],"effect":["[Digivolve] Lv.3 w/[Agumon] in name: Cost 2[Security] You may play 1 [Agumon] or 1 Tamer card with [Tai Kamiya] in its name from your hand or trash without paying the cost. ＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST15-08","card_level":"SR","image_link":"https://i.imgur.com/LvD0TXc.png","LOCAL_NUMBER":16251},
{"name":"나이트몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 데이터 Warrior","cost":6,"evolution_cost":["3 from Lv.4","-"],"effect":["[On Play] Delete 1 of your opponent's Digimon with a play cost of 5 or less.","-","-"],"card_number":"ST15-09","card_level":"C","image_link":"https://i.imgur.com/KBl5Xul.png","LOCAL_NUMBER":16252},
{"name":"안드로몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","cost":7,"evolution_cost":["3 from Lv.4","-"],"effect":["[When Digivolving] ＜De-Digivolve 1＞ 1 of your opponent's Digimon. (Trash the top card. You can't trash past level 3 cards.)","-","-"],"card_number":"ST15-10","card_level":"U","image_link":"https://i.imgur.com/trJhLV9.png","LOCAL_NUMBER":16253},
{"name":"메탈그레이몬","color":"흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","cost":8,"evolution_cost":["3 from Lv.4","-"],"effect":["[Digivolve] Lv.4 w/[Greymon] in name: Cost 3＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST15-11","card_level":"R","image_link":"https://i.imgur.com/1ZYs7bC.png","LOCAL_NUMBER":16254},
{"name":"워그레이몬 ACE","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Dragonkin","cost":6,"evolution_cost":["3 from Lv.5","-"],"effect":["[Digivolve] Lv.5 w/[Greymon] in name: Cost 3[Hand][Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) ＜Blocker＞ [All Turns][Once Per Turn] When a card is removed from a security stack, you may unsuspend this Digimon.","-","-"],"card_number":"ST15-12","card_level":"SR","image_link":"https://i.imgur.com/pu1vGv2.png","LOCAL_NUMBER":16255},
{"name":"하이안드로몬","color":"흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Cyborg","cost":11,"evolution_cost":["4 from Lv.5","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target. [When Digivolving] Delete 1 of your opponent's Digimon with a play cost of 8 or less.","-","-"],"card_number":"ST15-13","card_level":"U","image_link":"https://i.imgur.com/Za3uH9G.png","LOCAL_NUMBER":16256},
{"name":"신태일(디지몬 시리즈)|신태일","color":"흑","type":"테이머","attribute":"- -","cost":4,"evolution_cost":["-","-"],"effect":["[Start of Your Turn] If you have 2 or fewer memory, set it to 3. [All Turns] When an attack target is switched, by suspending this Tamer, ＜Draw 1＞ and 1 of your Digimon gets +2000 DP until the end of the turn.","-","-"],"card_number":"ST15-14","card_level":"R","image_link":"https://i.imgur.com/2wk3OgR.png","LOCAL_NUMBER":16257},
{"name":"용기의전진","color":"흑","type":"Opiton","attribute":"- -","cost":4,"evolution_cost":["-","-"],"effect":["While you have a Tamer with [Tai Kamiya] in its name, you may use this card without meeting its color requirements. [Main] Unsuspend 1 of your Digimon. Then, 1 of your Digimon with [Greymon] in its name isn't affected by the effects of your opponent's Digimon until the end of your opponent's turn.","-","-"],"card_number":"ST15-15","card_level":"U","image_link":"https://i.imgur.com/1oKOs1x.png","LOCAL_NUMBER":16258},
{"name":"트라이던트 암","color":"흑","type":"Opiton","attribute":"- -","cost":6,"evolution_cost":["-","-"],"effect":["[Main] ＜De-Digivolve 3＞ 1 of your opponent's Digimon. Then, until the end of your opponent's turn, 1 of your opponent's Digimon gains \"[Start of Your Main Phase] This Digimon attacks.\"","-","-"],"card_number":"ST15-16","card_level":"C","image_link":"https://i.imgur.com/wtR18Df.png","LOCAL_NUMBER":16259}
]