
ST16=
[


    {"name":"뿔몬","color":"자","level":2,"type":"디지타마","attribute":"유년기 - Lesser","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST16-01","card_level":"U","image_link":"https://i.imgur.com/sIssMqX.png","LOCAL_NUMBER":16260},
{"name":"에렉몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 바이러스 Mammal","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[On Play] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand.","-","-"],"card_number":"ST16-02","card_level":"C","image_link":"https://i.imgur.com/3BIC5z0.png","LOCAL_NUMBER":16261},
{"name":"파피몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Reptile","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["[Digivolve] [Tsunomon]: Cost 0[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory.","-","-"],"card_number":"ST16-03","card_level":"R","image_link":"https://i.imgur.com/5pY8WIv.png","LOCAL_NUMBER":16262},
{"name":"테이파몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 백신 Holy Beast","cost":3,"evolution_cost":["0 from Lv.2","-"],"effect":["-","-","-"],"card_number":"ST16-04","card_level":"U","image_link":"https://i.imgur.com/sum9n2f.png","LOCAL_NUMBER":16263},
{"name":"울퉁몬","color":"자","level":3,"type":"디지몬","attribute":"성장기 데이터 Rock","cost":4,"evolution_cost":["0 from Lv.2","-"],"effect":["＜Retaliation＞ (When this Digimon is deleted in battle, delete the Digimon it battled.) [Your Turn] When this Digimon attacks an opponent's Digimon, lose 2 memory.","-","-"],"card_number":"ST16-05","card_level":"C","image_link":"https://i.imgur.com/zTFxLsj.png","LOCAL_NUMBER":16264},
{"name":"고스몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Ghost","cost":4,"evolution_cost":["2 from Lv.3","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST16-06","card_level":"C","image_link":"https://i.imgur.com/UdooJtO.png","LOCAL_NUMBER":16265},
{"name":"메라몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 데이터 Flame","cost":5,"evolution_cost":["2 from Lv.3","-"],"effect":["[On Deletion] Gain 1 memory.","-","-"],"card_number":"ST16-07","card_level":"C","image_link":"https://i.imgur.com/KuJw6Hh.png","LOCAL_NUMBER":16266},
{"name":"가루몬","color":"자","level":4,"type":"디지몬","attribute":"성숙기 백신 Beast","cost":6,"evolution_cost":["2 from Lv.3","-"],"effect":["[Digivolve] Lv.3 w/[Gabumon] in name: Cost 2[Security] You may play 1 [Gabumon] or 1 Tamer card with [Matt Ishida] in its name from your hand or trash without paying the cost. [When Digivolving] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand.","-","-"],"card_number":"ST16-08","card_level":"SR","image_link":"https://i.imgur.com/ppsDxW1.png","LOCAL_NUMBER":16267},
{"name":"펌프몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 데이터 Puppet","cost":6,"evolution_cost":["3 from Lv.4","-"],"effect":["[On Play] You may play 1 purple level 3 Digimon card from your trash without paying the cost.","-","-"],"card_number":"ST16-09","card_level":"C","image_link":"https://i.imgur.com/WxMkikf.png","LOCAL_NUMBER":16268},
{"name":"맘몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 백신 Ancient Animal","cost":7,"evolution_cost":["3 from Lv.4","-"],"effect":["＜Blocker＞ (At blocker timing, by suspending this Digimon, it becomes the attack target.)","-","-"],"card_number":"ST16-10","card_level":"U","image_link":"https://i.imgur.com/219j0x9.png","LOCAL_NUMBER":16269},
{"name":"워가루몬","color":"자","level":5,"type":"디지몬","attribute":"완전체 백신 Beastkin","cost":8,"evolution_cost":["3 from Lv.4","-"],"effect":["[Digivolve] Lv.4 w/[Garurumon] in name: Cost 3[When Attacking][Once Per Turn] By trashing 1 card in your hand, unsuspend this Digimon.","-","-"],"card_number":"ST16-11","card_level":"R","image_link":"https://i.imgur.com/RggzBH8.png","LOCAL_NUMBER":16270},
{"name":"메탈가루몬 ACE","color":"자","level":6,"type":"디지몬","attribute":"궁극체 데이터 Cyborg","cost":6,"evolution_cost":["3 from Lv.5","-"],"effect":["[Digivolve] Lv.5 w/[Garurumon] in name: Cost 3[Hand][Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) [When Digivolving] By trashing up to 3 cards in your hand, gain 1 memory for each card trashed. [When Attacking][Once Per Turn] By trashing 1 card in your hand, delete 1 of your opponent's Digimon with the lowest level.","-","-"],"card_number":"ST16-12","card_level":"SR","image_link":"https://i.imgur.com/dMm4dGI.png","LOCAL_NUMBER":16271},
{"name":"스컬맘몬","color":"자","level":6,"type":"디지몬","attribute":"궁극체 백신 Undead","cost":11,"evolution_cost":["4 from Lv.5","-"],"effect":["[When Digivolving] ＜Draw 1＞. (Draw 1 card from your deck.) Then, trash 1 card in your hand. [All Turns][Once Per Turn] When one of your effects trashes a card in your hand, you may play 1 level 4 or lower purple Digimon card from your trash without paying the cost.","-","-"],"card_number":"ST16-13","card_level":"U","image_link":"https://i.imgur.com/subkrCo.png","LOCAL_NUMBER":16272},
{"name":"매튜","color":"자","type":"테이머","attribute":"- -","cost":4,"evolution_cost":["-","-"],"effect":["[Start of Your Turn] If you have 2 or fewer memory, set it to 3. [All Turns] When one of your effects trashes a card in your hand, by suspending this Tamer, gain 1 memory.","-","-"],"card_number":"ST16-14","card_level":"R","image_link":"https://i.imgur.com/f9QtrQK.png","LOCAL_NUMBER":16273},
{"name":"우정의통곡","color":"자","type":"Opiton","attribute":"- -","cost":3,"evolution_cost":["-","-"],"effect":["While you have a Tamer with [Matt Ishida] in its name, you may use this card without meeting its color requirements.[Main] Return 1 Digimon card from your trash to the hand. Then, 1 of your Digimon with [Garurumon] in its name gains \"[On Deletion] Play this card without paying the cost\" until the end of your opponent's turn.","-","-"],"card_number":"ST16-15","card_level":"U","image_link":"https://i.imgur.com/fXulq8J.png","LOCAL_NUMBER":16274},
{"name":"볼 디블로","color":"자","type":"Opiton","attribute":"- -","cost":4,"evolution_cost":["-","-"],"effect":["[Main] Delete 1 of your opponent's level 5 or lower Digimon.","-","-"],"card_number":"ST16-16","card_level":"C","image_link":"https://i.imgur.com/GEpPTdj.png","LOCAL_NUMBER":16275}
]