
ST17=
[


    {"name":"구미몬","color":"녹","level":2,"type":"디지타마","attribute":"유년기 - Lesser","cost":"-","evolution_cost":["-","-"],"effect":["-","-","-"],"card_number":"ST17-01","card_level":"U","image_link":"https://i.imgur.com/dfgiyfG.png","LOCAL_NUMBER":16276},
{"name":"테리어몬","color":"녹","level":3,"type":"디지몬","attribute":"성장기 백신 Beast","cost":3,"evolution_cost":["0 from Lv.3","-"],"effect":["[Digivolve] [Gummymon]: Cost 0[Main] [Once Per Turn] You may play 1 green Tamer card or 1 level 3 Digimon card with [Lopmon] in its name from your hand with the play cost reduced by 2.","-","-"],"card_number":"ST17-02","card_level":"SR","image_link":"https://i.imgur.com/CX96kpV.png","LOCAL_NUMBER":16277},
{"name":"로프몬","color":"녹","level":3,"type":"디지몬","attribute":"성장기 데이터 Beast","cost":3,"evolution_cost":["0 from Lv.3","-"],"effect":["[Digivolve] [Kokomon]: Cost 0[Main] [Once Per Turn] 1 of your Digimon gains ＜Alliance＞ for the turn.","-","-"],"card_number":"ST17-03","card_level":"SR","image_link":"https://i.imgur.com/OErKVHJ.png","LOCAL_NUMBER":16278},
{"name":"웬디몬","color":"녹자","level":4,"type":"디지몬","attribute":"성숙기 바이러스 Beastkin","cost":5,"evolution_cost":["3 from Lv.4","3 from Lv.3"],"effect":["[Digivolve] Lv.3 w/[Terriermon]/[Lopmon] in name: Cost 2[On Play] [When Digivolving] Delete 1 level 3 or lower Digimon. If this effect deleted one of your Digimon, you may play 1 level 3 Digimon card with [Terriermon] or [Lopmon] in its name from your trash without paying the cost.","-","-"],"card_number":"ST17-04","card_level":"U","image_link":"https://i.imgur.com/sTKzU35.png","LOCAL_NUMBER":16279},
{"name":"가르고몬","color":"녹흑","level":4,"type":"디지몬","attribute":"성숙기 백신 Beastkin","cost":6,"evolution_cost":["3 from Lv.4","3 from Lv.3"],"effect":["[Digivolve] Lv.3 w/[Terriermon]/[Lopmon] in name: Cost 2[Your Turn] [Once Per Turn] When this Digimon becomes suspended, 1 of your Digimon gains ＜Jamming＞ for the turn.","-","-"],"card_number":"ST17-05","card_level":"C","image_link":"https://i.imgur.com/8QLkyRl.png","LOCAL_NUMBER":16280},
{"name":"래피드몬(아머체)","color":"녹황","level":4,"type":"디지몬","attribute":"Armor Form 백신 Holy Warrior","cost":7,"evolution_cost":["4 from Lv.4","4 from Lv.3"],"effect":["[Digivolve] Lv.3 w/[Terriermon] in name: Cost 3＜Blocker＞ ＜Armor Purge＞ [All Turns] [Once Per Turn] When this Digimon becomes suspended, 1 of your opponent's Digimon and all of their Security Digimon get -4000 DP until the end of their turn.","-","-"],"card_number":"ST17-06","card_level":"SR","image_link":"https://i.imgur.com/RXEuaXo.png","LOCAL_NUMBER":16281},
{"name":"래피드몬","color":"녹흑","level":5,"type":"디지몬","attribute":"완전체 백신 Cyborg","cost":7,"evolution_cost":["4 from Lv.5","4 from Lv.4"],"effect":["[Digivolve] Lv.4 w/[Gargomon]/[Rapidmon] in name: Cost 3[On Play] [When Digivolving] ＜De-Digivolve 1＞ 1 of your opponent's Digimon. Then, if you have a green Tamer, until the end of your opponent's turn, your opponent's effects can't delete this Digimon or return it to the hand or deck.","-","-"],"card_number":"ST17-07","card_level":"C","image_link":"https://i.imgur.com/Mq3uwDR.png","LOCAL_NUMBER":16282},
{"name":"세인트가르고몬 ACE","color":"녹흑","level":6,"type":"디지몬","attribute":"궁극체 백신 Machine","cost":7,"evolution_cost":["4 from Lv.6","4 from Lv.5"],"effect":["[Digivolve] [Rapidmon] in name: Cost 5[Hand] [Counter] ＜Blast Digivolve＞ (One of your Digimon may digivolve into this card without paying the cost.) ＜Blocker＞ ＜Reboot＞ [When Digivolving] Suspend 2 of your opponent's Digimon or Tamers. Then, 2 of their Digimon or Tamers can't unsuspend or digivolve until the end of their turn. [When Digivolving] [End of Attack] [Once Per Turn] You may unsuspend this Digimon.","-","-"],"card_number":"ST17-08","card_level":"SR","image_link":"https://i.imgur.com/f5wJzuX.png","LOCAL_NUMBER":16283},
{"name":"케루비몬(악)","color":"녹자","level":6,"type":"디지몬","attribute":"궁극체 백신 Cherub","cost":12,"evolution_cost":["4 from Lv.6","4 from Lv.5"],"effect":["[Digivolve] [Antylamon]: Cost 3＜Alliance＞ [When Digivolving] You may delete 1 level 4 or lower Digimon. Then, you may play 1 level 4 or lower green or purple Digimon card from your hand or trash without paying the cost.","-","-"],"card_number":"ST17-09","card_level":"R","image_link":"https://i.imgur.com/EtMAJef.png","LOCAL_NUMBER":16284},
{"name":"곽소룡","color":"녹","type":"테이머","attribute":"- -","cost":3,"evolution_cost":["-","-"],"effect":["[Start of Your Main Phase] If your opponent has a Digimon, gain 1 memory. [Main] By placing this Tamer and 1 [Gargomon] and 1 [Rapidmon] from your trash in any order as one of your [Terriermon]'s bottom digivolution cards, that Digimon may digivolve into [MegaGargomon] in the hand for a digivolution cost of 4, ignoring its digivolution requirements. If this effect digivolved, that Digimon gains ＜Rush＞ for the turn.","-","-"],"card_number":"ST17-10","card_level":"R","image_link":"https://i.imgur.com/71SodIj.png","LOCAL_NUMBER":16285},
{"name":"더블 타이푼","color":"녹","type":"옵션","attribute":"- -","cost":3,"evolution_cost":["-","-"],"effect":["[Main] Reveal the top 3 cards of your deck. Add 1 green Digimon card and 1 such Tamer card among them to the hand. Return the rest to the bottom of the deck. Then, place this card in the battle area. [Main] ＜Delay＞ ・ You may play 1 [Terriermon] or [Lopmon] from your hand without paying the cost.","-","-"],"card_number":"ST17-11","card_level":"R","image_link":"https://i.imgur.com/eiA9Jbv.png","LOCAL_NUMBER":16286},
{"name":"자이언트 미사일","color":"녹","type":"옵션","attribute":"- -","cost":8,"evolution_cost":["-","-"],"effect":["[Main] Suspend 1 of your opponent's Digimon. Then, return 1 of their suspended Digimon to the bottom of the deck. 1 of their Digimon can't unsuspend until the end of their turn.","-","-"],"card_number":"ST17-12","card_level":"U","image_link":"https://i.imgur.com/rFTrEi2.png","LOCAL_NUMBER":16287},
{"name":"매그너몬","color":"흑청","level":4,"type":"디지몬","attribute":"Armor Form 프리 Holy Warrior/Royal Knight","cost":7,"evolution_cost":["4 from Lv.4","4 from Lv.3"],"effect":["[Digivolve] [Veemon]: Cost 3[Security] ＜De-Digivolve 1＞ 1 Digimon. At the end of the battle, 1 of your Digimon may digivolve into this card without paying the digivolution cost. ＜Blocker＞ ＜Armor Purge＞ [When Digivolving] Trash the top digivolution card of 1 of your opponent's Digimon for each of that Digimon's colors. Then, return 1 of your opponent's Digimon with no digivolution cards to the hand.","-","-"],"card_number":"ST17-13","card_level":"SR","image_link":"https://i.imgur.com/ScnynmD.png","LOCAL_NUMBER":16288}
]